    let postalCodeBelgium = `
    [
      {"Code": "1000", "Name": "Bruxelles", "Catchment": "Yes"},
      {"Code": "1005", "Name": "Conseil Region Bruxelles-Capitale", "Catchment": "Yes"},
      {"Code": "1006", "Name": "Raad Vlaamse Gemeenschapscommissie", "Catchment": "Yes"},
      {"Code": "1007", "Name": "Ass. Commiss. Communau. française", "Catchment": "Yes"},
      {"Code": "1008", "Name": "Chambre des Représentants", "Catchment": "Yes"},
      {"Code": "1009", "Name": "Senat de Belgique", "Catchment": "Yes"},
      {"Code": "1010", "Name": "Cité Administrative de l'Etat", "Catchment": "Yes"},
      {"Code": "1011", "Name": "Vlaamse Raad - Vlaams Parlement", "Catchment": "Yes"},
      {"Code": "1012", "Name": "Parlement de la Communauté française", "Catchment": "Yes"},
      {"Code": "1020", "Name": "Bruxelles Laeken", "Catchment": "Yes"},
      {"Code": "1030", "Name": "Bruxelles", "Catchment": "Yes"},
      {"Code": "1031", "Name": "Organisations Sociales Chrétiennes", "Catchment": "Yes"},
      {"Code": "1040", "Name": "Bruxelles Etterbeek", "Catchment": "Yes"},
      {"Code": "1041", "Name": "International Press Center", "Catchment": "Yes"},
      {"Code": "1043", "Name": "VRT", "Catchment": "Yes"},
      {"Code": "1044", "Name": "RTBF", "Catchment": "Yes"},
      {"Code": "1045", "Name": "D.I.V.", "Catchment": "Yes"},
      {"Code": "1047", "Name": "Parlement Européen", "Catchment": "Yes"},
      {"Code": "1048", "Name": "U.E.-Conseil", "Catchment": "Yes"},
      {"Code": "1049", "Name": "U.E.-Commission", "Catchment": "Yes"},
      {"Code": "1050", "Name": "Bruxelles", "Catchment": "Yes"},
      {"Code": "1060", "Name": "Bruxelles Saint-Gilles", "Catchment": "Yes"},
      {"Code": "1070", "Name": "Bruxelles Anderlecht", "Catchment": "Yes"},
      {"Code": "1080", "Name": "Bruxelles Molenbeek-Saint-Jean", "Catchment": "Yes"},
      {"Code": "1081", "Name": "Bruxelles Koekelberg", "Catchment": "Yes"},
      {"Code": "1082", "Name": "Bruxelles Berchem-Sainte-Agathe", "Catchment": "Yes"},
      {"Code": "1083", "Name": "Bruxelles Ganshoren", "Catchment": "Yes"},
      {"Code": "1090", "Name": "Bruxelles", "Catchment": "Yes"},
      {"Code": "1110", "Name": "OTAN - NATO", "Catchment": "Yes"},
      {"Code": "1120", "Name": "Bruxelles Nederover-Heembeek", "Catchment": "Yes"},
      {"Code": "1130", "Name": "Bruxelles", "Catchment": "Yes"},
      {"Code": "1140", "Name": "Bruxelles Evere", "Catchment": "Yes"},
      {"Code": "1150", "Name": "Bruxelles Woluwe-Saint-Pierre", "Catchment": "Yes"},
      {"Code": "1160", "Name": "Bruxelles", "Catchment": "Yes"},
      {"Code": "1170", "Name": "Bruxelles", "Catchment": "Yes"},
      {"Code": "1180", "Name": "Bruxelles Uccle", "Catchment": "Yes"},
      {"Code": "1190", "Name": "Bruxelles Forest", "Catchment": "Yes"},
      {"Code": "1200", "Name": "Bruxelles Woluwé-Saint-Lambert", "Catchment": "Yes"},
      {"Code": "1201", "Name": "R.T.L. - T.V.I.", "Catchment": "Yes"},
      {"Code": "1210", "Name": "Bruxelles Saint-Josseten-Noode", "Catchment": "Yes"},
      {"Code": "1212", "Name": "SPF Mobilité", "Catchment": "Yes"},
      {"Code": "1500", "Name": "Halle", "Catchment": "Yes"},
      {"Code": "1501", "Name": "Halle", "Catchment": "Yes"},
      {"Code": "1502", "Name": "Halle Lembeek", "Catchment": "Yes"},
      {"Code": "1540", "Name": "Herne Herfelingen", "Catchment": "Yes"},
      {"Code": "1541", "Name": "Herne Sint-Pieters-Kapelle", "Catchment": "Yes"},
      {"Code": "1547", "Name": "Bever", "Catchment": "Yes"},
      {"Code": "1560", "Name": "Hoeilaart", "Catchment": "Yes"},
      {"Code": "1570", "Name": "Galmaarden", "Catchment": "Yes"},
      {"Code": "1600", "Name": "Sint-Pieters-Leeuw", "Catchment": "Yes"},
      {"Code": "1601", "Name": "Sint-Pieters-Leeuw Ruisbroek", "Catchment": "Yes"},
      {"Code": "1602", "Name": "Sint-Pieters-Leeuw Vlezenbeek", "Catchment": "Yes"},
      {"Code": "1620", "Name": "Drogenbos", "Catchment": "Yes"},
      {"Code": "1630", "Name": "Linkebeek", "Catchment": "Yes"},
      {"Code": "1640", "Name": "Sint-Genesius-Rode", "Catchment": "Yes"},
      {"Code": "1650", "Name": "Beersel", "Catchment": "Yes"},
      {"Code": "1651", "Name": "Beersel", "Catchment": "Yes"},
      {"Code": "1652", "Name": "Beersel", "Catchment": "Yes"},
      {"Code": "1653", "Name": "Beersel Dworp", "Catchment": "Yes"},
      {"Code": "1654", "Name": "Beersel Huizingen", "Catchment": "Yes"},
      {"Code": "1670", "Name": "Pepingen Heikruis", "Catchment": "Yes"},
      {"Code": "1671", "Name": "Pepingen Elingen", "Catchment": "Yes"},
      {"Code": "1673", "Name": "Pepingen Beert", "Catchment": "Yes"},
      {"Code": "1674", "Name": "Pepingen Bellingen", "Catchment": "Yes"},
      {"Code": "1700", "Name": "Dilbeek", "Catchment": "Yes"},
      {"Code": "1701", "Name": "Dilbeek", "Catchment": "Yes"},
      {"Code": "1702", "Name": "Dilbeek Groot-Bijgaarden", "Catchment": "Yes"},
      {"Code": "1703", "Name": "Dilbeek Schepdaal", "Catchment": "Yes"},
      {"Code": "1730", "Name": "Asse Mollem", "Catchment": "Yes"},
      {"Code": "1731", "Name": "Asse Relegem", "Catchment": "Yes"},
      {"Code": "1740", "Name": "Ternat", "Catchment": "Yes"},
      {"Code": "1741", "Name": "Ternat Wambeek", "Catchment": "Yes"},
      {"Code": "1742", "Name": "Ternat Sint-Katherina-Lombeek", "Catchment": "Yes"},
      {"Code": "1745", "Name": "Opwijk Mazenzele", "Catchment": "Yes"},
      {"Code": "1750", "Name": "Lennik", "Catchment": "Yes"},
      {"Code": "1755", "Name": "Gooik Oetingen", "Catchment": "Yes"},
      {"Code": "1760", "Name": "Roosdaal Pamel", "Catchment": "Yes"},
      {"Code": "1761", "Name": "Roosdaal", "Catchment": "Yes"},
      {"Code": "1770", "Name": "Liedekerke", "Catchment": "Yes"},
      {"Code": "1780", "Name": "Wemmel", "Catchment": "Yes"},
      {"Code": "1785", "Name": "Merchtem Hamme", "Catchment": "Yes"},
      {"Code": "1790", "Name": "Affligem Essene", "Catchment": "Yes"},
      {"Code": "1800", "Name": "Vilvoorde Peutie", "Catchment": "Yes"},
      {"Code": "1804", "Name": "Cargovil", "Catchment": "Yes"},
      {"Code": "1818", "Name": "VTM", "Catchment": "Yes"},
      {"Code": "1820", "Name": "Steenokkerzeel Perk", "Catchment": "Yes"},
      {"Code": "1830", "Name": "Machelen", "Catchment": "Yes"},
      {"Code": "1831", "Name": "Machelen", "Catchment": "Yes"},
      {"Code": "1840", "Name": "Londerzeel", "Catchment": "Yes"},
      {"Code": "1850", "Name": "Grimbergen", "Catchment": "Yes"},
      {"Code": "1851", "Name": "Grimbergen Humbeek", "Catchment": "Yes"},
      {"Code": "1852", "Name": "Grimbergen", "Catchment": "Yes"},
      {"Code": "1853", "Name": "Grimbergen Strombeek-Bever", "Catchment": "Yes"},
      {"Code": "1860", "Name": "Meise", "Catchment": "Yes"},
      {"Code": "1861", "Name": "Meise Wolvertem", "Catchment": "Yes"},
      {"Code": "1880", "Name": "Kapelleopden-Bos Ramsdonk", "Catchment": "Yes"},
      {"Code": "1910", "Name": "Kampenhout Buken", "Catchment": "Yes"},
      {"Code": "1930", "Name": "Zaventem", "Catchment": "Yes"},
      {"Code": "1931", "Name": "Brucargo", "Catchment": "Yes"},
      {"Code": "1932", "Name": "Zaventem", "Catchment": "Yes"},
      {"Code": "1933", "Name": "Zaventem Sterrebeek", "Catchment": "Yes"},
      {"Code": "1934", "Name": "Bruxelles X-Aeroport Remailing", "Catchment": "Yes"},
      {"Code": "1950", "Name": "Kraainem", "Catchment": "Yes"},
      {"Code": "1970", "Name": "Wezembeek-Oppem", "Catchment": "Yes"},
      {"Code": "1980", "Name": "Zemst", "Catchment": "Yes"},
      {"Code": "1981", "Name": "Zemst Hofstade", "Catchment": "Yes"},
      {"Code": "1982", "Name": "Zemst Weerde", "Catchment": "Yes"},
      {"Code": "2000", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2018", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2020", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2030", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2040", "Name": "Antwerpen Berendrecht-Zandvliet-Lillo, Lillo", "Catchment": "Yes"},
      {"Code": "2050", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2060", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2070", "Name": "Zwijndrecht", "Catchment": "Yes"},
      {"Code": "2100", "Name": "Antwerpen Deurne", "Catchment": "Yes"},
      {"Code": "2110", "Name": "Wijnegem", "Catchment": "Yes"},
      {"Code": "2140", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2150", "Name": "Borsbeek", "Catchment": "Yes"},
      {"Code": "2160", "Name": "Wommelgem", "Catchment": "Yes"},
      {"Code": "2170", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2180", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2200", "Name": "Herentals Morkhoven", "Catchment": "Yes"},
      {"Code": "2220", "Name": "Heistopden-Berg", "Catchment": "Yes"},
      {"Code": "2221", "Name": "Heistopden-Berg Booischot", "Catchment": "Yes"},
      {"Code": "2222", "Name": "Heistopden-Berg Wiekevorst", "Catchment": "Yes"},
      {"Code": "2223", "Name": "Heistopden-Berg Schriek", "Catchment": "Yes"},
      {"Code": "2230", "Name": "Herselt", "Catchment": "Yes"},
      {"Code": "2235", "Name": "Hulshout", "Catchment": "Yes"},
      {"Code": "2240", "Name": "Zandhoven Viersel", "Catchment": "Yes"},
      {"Code": "2242", "Name": "Zandhoven", "Catchment": "Yes"},
      {"Code": "2243", "Name": "Zandhoven Pulle", "Catchment": "Yes"},
      {"Code": "2250", "Name": "Olen", "Catchment": "Yes"},
      {"Code": "2260", "Name": "Westerlo Zoerle-Parwijs", "Catchment": "Yes"},
      {"Code": "2270", "Name": "Herenthout", "Catchment": "Yes"},
      {"Code": "2275", "Name": "Lille Wechelderzande", "Catchment": "Yes"},
      {"Code": "2280", "Name": "Grobbendonk", "Catchment": "Yes"},
      {"Code": "2288", "Name": "Grobbendonk", "Catchment": "Yes"},
      {"Code": "2290", "Name": "Vorselaar", "Catchment": "Yes"},
      {"Code": "2300", "Name": "Turnhout", "Catchment": "Yes"},
      {"Code": "2310", "Name": "Rijkevorsel", "Catchment": "Yes"},
      {"Code": "2320", "Name": "Hoogstraten", "Catchment": "Yes"},
      {"Code": "2321", "Name": "Hoogstraten Meer", "Catchment": "Yes"},
      {"Code": "2322", "Name": "Hoogstraten", "Catchment": "Yes"},
      {"Code": "2323", "Name": "Hoogstraten Wortel", "Catchment": "Yes"},
      {"Code": "2328", "Name": "Hoogstraten", "Catchment": "Yes"},
      {"Code": "2330", "Name": "Merksplas", "Catchment": "Yes"},
      {"Code": "2340", "Name": "Beerse", "Catchment": "Yes"},
      {"Code": "2350", "Name": "Vosselaar", "Catchment": "Yes"},
      {"Code": "2360", "Name": "Oud-Turnhout", "Catchment": "Yes"},
      {"Code": "2370", "Name": "Arendonk", "Catchment": "Yes"},
      {"Code": "2380", "Name": "Ravels", "Catchment": "Yes"},
      {"Code": "2381", "Name": "Ravels", "Catchment": "Yes"},
      {"Code": "2382", "Name": "Ravels", "Catchment": "Yes"},
      {"Code": "2387", "Name": "Baarle-Hertog", "Catchment": "Yes"},
      {"Code": "2390", "Name": "Malle", "Catchment": "Yes"},
      {"Code": "2400", "Name": "Mol", "Catchment": "Yes"},
      {"Code": "2430", "Name": "Laakdal Vorst", "Catchment": "Yes"},
      {"Code": "2431", "Name": "Herselt Varendonk", "Catchment": "Yes"},
      {"Code": "2440", "Name": "Geel", "Catchment": "Yes"},
      {"Code": "2450", "Name": "Meerhout", "Catchment": "Yes"},
      {"Code": "2460", "Name": "Kasterlee Tielen", "Catchment": "Yes"},
      {"Code": "2470", "Name": "Retie", "Catchment": "Yes"},
      {"Code": "2480", "Name": "Dessel", "Catchment": "Yes"},
      {"Code": "2490", "Name": "Balen", "Catchment": "Yes"},
      {"Code": "2491", "Name": "Balen Olmen", "Catchment": "Yes"},
      {"Code": "2500", "Name": "Lier", "Catchment": "Yes"},
      {"Code": "2520", "Name": "Ranst Emblem", "Catchment": "Yes"},
      {"Code": "2530", "Name": "Boechout", "Catchment": "Yes"},
      {"Code": "2531", "Name": "Boechout Vremde", "Catchment": "Yes"},
      {"Code": "2540", "Name": "Hove", "Catchment": "Yes"},
      {"Code": "2547", "Name": "Lint", "Catchment": "Yes"},
      {"Code": "2550", "Name": "Kontich", "Catchment": "Yes"},
      {"Code": "2560", "Name": "Nijlen Bevel", "Catchment": "Yes"},
      {"Code": "2570", "Name": "Duffel", "Catchment": "Yes"},
      {"Code": "2580", "Name": "Putte Beerzel", "Catchment": "Yes"},
      {"Code": "2590", "Name": "Berlaar Gestel", "Catchment": "Yes"},
      {"Code": "2600", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2610", "Name": "Antwerpen", "Catchment": "Yes"},
      {"Code": "2620", "Name": "Hemiksem", "Catchment": "Yes"},
      {"Code": "2627", "Name": "Schelle", "Catchment": "Yes"},
      {"Code": "2630", "Name": "Aartselaar", "Catchment": "Yes"},
      {"Code": "2640", "Name": "Mortsel", "Catchment": "Yes"},
      {"Code": "2650", "Name": "Edegem", "Catchment": "Yes"},
      {"Code": "2660", "Name": "Antwerpen Hoboken", "Catchment": "Yes"},
      {"Code": "2800", "Name": "Mechelen", "Catchment": "Yes"},
      {"Code": "2801", "Name": "Mechelen Heffen", "Catchment": "Yes"},
      {"Code": "2811", "Name": "Mechelen Hombeek", "Catchment": "Yes"},
      {"Code": "2812", "Name": "Mechelen Muizen", "Catchment": "Yes"},
      {"Code": "2820", "Name": "Bonheiden", "Catchment": "Yes"},
      {"Code": "2830", "Name": "Willebroek Tisselt", "Catchment": "Yes"},
      {"Code": "2840", "Name": "Rumst Terhagen", "Catchment": "Yes"},
      {"Code": "2845", "Name": "Niel", "Catchment": "Yes"},
      {"Code": "2850", "Name": "Boom", "Catchment": "Yes"},
      {"Code": "2860", "Name": "Sint-Katelijne-Waver", "Catchment": "Yes"},
      {"Code": "2861", "Name": "Sint-Katelijne-Waver Onze-Lieve-Vrouw-Waver", "Catchment": "Yes"},
      {"Code": "2870", "Name": "Puurs Ruisbroek", "Catchment": "Yes"},
      {"Code": "2880", "Name": "Bornem Hingene", "Catchment": "Yes"},
      {"Code": "2890", "Name": "Sint-Amands Lippelo", "Catchment": "Yes"},
      {"Code": "2900", "Name": "Schoten", "Catchment": "Yes"},
      {"Code": "2910", "Name": "Essen", "Catchment": "Yes"},
      {"Code": "2920", "Name": "Kalmthout", "Catchment": "Yes"},
      {"Code": "2930", "Name": "Brasschaat", "Catchment": "Yes"},
      {"Code": "2940", "Name": "Stabroek Hoevenen", "Catchment": "Yes"},
      {"Code": "2950", "Name": "Kapellen", "Catchment": "Yes"},
      {"Code": "2960", "Name": "Brecht Sint-Jobin't-Goor", "Catchment": "Yes"},
      {"Code": "2970", "Name": "Schilde 's Gravenwezel", "Catchment": "Yes"},
      {"Code": "2980", "Name": "Zoersel Halle", "Catchment": "Yes"},
      {"Code": "2990", "Name": "Wuustwezel", "Catchment": "Yes"},
      {"Code": "3000", "Name": "Leuven", "Catchment": "Yes"},
      {"Code": "3001", "Name": "Leuven", "Catchment": "Yes"},
      {"Code": "3010", "Name": "Leuven", "Catchment": "Yes"},
      {"Code": "3012", "Name": "Leuven Wilsele", "Catchment": "Yes"},
      {"Code": "3018", "Name": "Leuven Wijgmaal", "Catchment": "Yes"},
      {"Code": "3020", "Name": "Herent Winksele", "Catchment": "Yes"},
      {"Code": "3040", "Name": "Huldenberg Neerijse", "Catchment": "Yes"},
      {"Code": "3050", "Name": "Oud-Heverlee", "Catchment": "Yes"},
      {"Code": "3051", "Name": "Oud-Heverlee Sint-Joris-Weert", "Catchment": "Yes"},
      {"Code": "3052", "Name": "Oud-Heverlee Blanden", "Catchment": "Yes"},
      {"Code": "3053", "Name": "Oud-Heverlee Haasrode", "Catchment": "Yes"},
      {"Code": "3054", "Name": "Oud-Heverlee", "Catchment": "Yes"},
      {"Code": "3060", "Name": "Bertem", "Catchment": "Yes"},
      {"Code": "3061", "Name": "Bertem Leefdaal", "Catchment": "Yes"},
      {"Code": "3070", "Name": "Kortenberg", "Catchment": "Yes"},
      {"Code": "3071", "Name": "Kortenberg Erps-Kwerps", "Catchment": "Yes"},
      {"Code": "3078", "Name": "Kortenberg Everberg", "Catchment": "Yes"},
      {"Code": "3080", "Name": "Tervuren Vossem", "Catchment": "Yes"},
      {"Code": "3090", "Name": "Overijse Terlanen", "Catchment": "Yes"},
      {"Code": "3110", "Name": "Rotselaar", "Catchment": "Yes"},
      {"Code": "3111", "Name": "Rotselaar Wezemaal", "Catchment": "Yes"},
      {"Code": "3118", "Name": "Rotselaar Werchter", "Catchment": "Yes"},
      {"Code": "3120", "Name": "Tremelo", "Catchment": "Yes"},
      {"Code": "3128", "Name": "Tremelo", "Catchment": "Yes"},
      {"Code": "3130", "Name": "Begijnendijk", "Catchment": "Yes"},
      {"Code": "3140", "Name": "Keerbergen", "Catchment": "Yes"},
      {"Code": "3150", "Name": "Haacht Wakkerzeel", "Catchment": "Yes"},
      {"Code": "3190", "Name": "Boortmeerbeek", "Catchment": "Yes"},
      {"Code": "3191", "Name": "Boortmeerbeek Hever", "Catchment": "Yes"},
      {"Code": "3200", "Name": "Aarschot", "Catchment": "Yes"},
      {"Code": "3201", "Name": "Aarschot", "Catchment": "Yes"},
      {"Code": "3202", "Name": "Aarschot Rillaar", "Catchment": "Yes"},
      {"Code": "3210", "Name": "Lubbeek", "Catchment": "Yes"},
      {"Code": "3211", "Name": "Lubbeek", "Catchment": "Yes"},
      {"Code": "3212", "Name": "Lubbeek", "Catchment": "Yes"},
      {"Code": "3220", "Name": "Holsbeek", "Catchment": "Yes"},
      {"Code": "3221", "Name": "Holsbeek Nieuwrode", "Catchment": "Yes"},
      {"Code": "3270", "Name": "Scherpenheuvel-Zichem Scherpenheuvel", "Catchment": "Yes"},
      {"Code": "3271", "Name": "Scherpenheuvel-Zichem", "Catchment": "Yes"},
      {"Code": "3272", "Name": "Scherpenheuvel-Zichem Testelt", "Catchment": "Yes"},
      {"Code": "3290", "Name": "Diest Webbekom", "Catchment": "Yes"},
      {"Code": "3293", "Name": "Diest", "Catchment": "Yes"},
      {"Code": "3294", "Name": "Diest Molenstede", "Catchment": "Yes"},
      {"Code": "3300", "Name": "Tienen Hakendover", "Catchment": "Yes"},
      {"Code": "3320", "Name": "Hoegaarden", "Catchment": "Yes"},
      {"Code": "3321", "Name": "Hoegaarden Outgaarden", "Catchment": "Yes"},
      {"Code": "3350", "Name": "Linter", "Catchment": "Yes"},
      {"Code": "3360", "Name": "Bierbeek Lovenjoel", "Catchment": "Yes"},
      {"Code": "3370", "Name": "Boutersem Roosbeek", "Catchment": "Yes"},
      {"Code": "3380", "Name": "Glabbeek", "Catchment": "Yes"},
      {"Code": "3381", "Name": "Glabbeek", "Catchment": "Yes"},
      {"Code": "3384", "Name": "Glabbeek", "Catchment": "Yes"},
      {"Code": "3390", "Name": "Tielt-Winge Sint-Joris-Winge", "Catchment": "Yes"},
      {"Code": "3391", "Name": "Tielt-Winge Meensel-Kiezegem", "Catchment": "Yes"},
      {"Code": "3400", "Name": "Landen Rumsdorp", "Catchment": "Yes"},
      {"Code": "3401", "Name": "Landen Walshoutem", "Catchment": "Yes"},
      {"Code": "3404", "Name": "Landen Neerlanden", "Catchment": "Yes"},
      {"Code": "3440", "Name": "Zoutleeuw", "Catchment": "Yes"},
      {"Code": "3450", "Name": "Geetbets", "Catchment": "Yes"},
      {"Code": "3454", "Name": "Geetbets", "Catchment": "Yes"},
      {"Code": "3460", "Name": "Bekkevoort Assent", "Catchment": "Yes"},
      {"Code": "3461", "Name": "Bekkevoort Molenbeek-Wersbeek", "Catchment": "Yes"},
      {"Code": "3470", "Name": "Kortenaken", "Catchment": "Yes"},
      {"Code": "3471", "Name": "Kortenaken", "Catchment": "Yes"},
      {"Code": "3472", "Name": "Kortenaken Kersbeek-Miskom", "Catchment": "Yes"},
      {"Code": "3473", "Name": "Kortenaken Waanrode", "Catchment": "Yes"},
      {"Code": "3500", "Name": "Hasselt Sint-Lambrechts-Herk", "Catchment": "Yes"},
      {"Code": "3501", "Name": "Hasselt Wimmertingen", "Catchment": "Yes"},
      {"Code": "3510", "Name": "Hasselt Kermt, Spalbeek", "Catchment": "Yes"},
      {"Code": "3511", "Name": "Hasselt, Stokrooie", "Catchment": "Yes"},
      {"Code": "3512", "Name": "Hasselt", "Catchment": "Yes"},
      {"Code": "3520", "Name": "Zonhoven", "Catchment": "Yes"},
      {"Code": "3530", "Name": "Houthalen-Helchteren Helchteren", "Catchment": "Yes"},
      {"Code": "3540", "Name": "Herkde-Stad", "Catchment": "Yes"},
      {"Code": "3545", "Name": "Halen Loksbergen", "Catchment": "Yes"},
      {"Code": "3550", "Name": "Heusden-Zolder Zolder", "Catchment": "Yes"},
      {"Code": "3560", "Name": "Lummen Linkhout", "Catchment": "Yes"},
      {"Code": "3570", "Name": "Alken", "Catchment": "Yes"},
      {"Code": "3580", "Name": "Beringen", "Catchment": "Yes"},
      {"Code": "3581", "Name": "Beringen Beverlo", "Catchment": "Yes"},
      {"Code": "3582", "Name": "Beringen Koersel", "Catchment": "Yes"},
      {"Code": "3583", "Name": "Beringen Paal", "Catchment": "Yes"},
      {"Code": "3590", "Name": "Diepenbeek", "Catchment": "Yes"},
      {"Code": "3600", "Name": "Diepenbeek Genk", "Catchment": "Yes"},
      {"Code": "3620", "Name": "Lanaken Gellik", "Catchment": "Yes"},
      {"Code": "3621", "Name": "Lanaken", "Catchment": "Yes"},
      {"Code": "3630", "Name": "Maasmechelen Opgrimbie", "Catchment": "Yes"},
      {"Code": "3631", "Name": "Maasmechelen Uikhoven", "Catchment": "Yes"},
      {"Code": "3640", "Name": "Kinrooi Geistingen", "Catchment": "Yes"},
      {"Code": "3650", "Name": "Dilsen-Stokkem Elen", "Catchment": "Yes"},
      {"Code": "3660", "Name": "Opglabbeek", "Catchment": "Yes"},
      {"Code": "3665", "Name": "As", "Catchment": "Yes"},
      {"Code": "3668", "Name": "As Nielbij-As", "Catchment": "Yes"},
      {"Code": "3670", "Name": "Meeuwen-Gruitrode Wijshagen", "Catchment": "Yes"},
      {"Code": "3680", "Name": "Maaseik Neeroeteren", "Catchment": "Yes"},
      {"Code": "3690", "Name": "Zutendaal", "Catchment": "Yes"},
      {"Code": "3700", "Name": "Tongeren 's Herenelderen", "Catchment": "Yes"},
      {"Code": "3717", "Name": "Herstappe", "Catchment": "Yes"},
      {"Code": "3720", "Name": "Kortessem", "Catchment": "Yes"},
      {"Code": "3721", "Name": "Kortessem", "Catchment": "Yes"},
      {"Code": "3722", "Name": "Kortessem", "Catchment": "Yes"},
      {"Code": "3723", "Name": "Kortessem", "Catchment": "Yes"},
      {"Code": "3724", "Name": "Kortessem", "Catchment": "Yes"},
      {"Code": "3730", "Name": "Hoeselt Romershoven", "Catchment": "Yes"},
      {"Code": "3732", "Name": "Hoeselt Schalkhoven", "Catchment": "Yes"},
      {"Code": "3740", "Name": "Bilzen Mopertingen, Rosmeer", "Catchment": "Yes"},
      {"Code": "3742", "Name": "Bilzen Martenslinde", "Catchment": "Yes"},
      {"Code": "3746", "Name": "Bilzen Hoelbeek", "Catchment": "Yes"},
      {"Code": "3770", "Name": "Riemst, Heukelom", "Catchment": "Yes"},
      {"Code": "3790", "Name": "Voeren", "Catchment": "Yes"},
      {"Code": "3791", "Name": "Voeren", "Catchment": "Yes"},
      {"Code": "3792", "Name": "Voeren Sint-Pieters-Voeren", "Catchment": "Yes"},
      {"Code": "3793", "Name": "Voeren", "Catchment": "Yes"},
      {"Code": "3798", "Name": "Voeren 's Gravenvoeren", "Catchment": "Yes"},
      {"Code": "3800", "Name": "Sint-Truiden Kerkombij-Sint-Truiden", "Catchment": "Yes"},
      {"Code": "3803", "Name": "Sint-Truiden Duras", "Catchment": "Yes"},
      {"Code": "3806", "Name": "Sint-Truiden Velm", "Catchment": "Yes"},
      {"Code": "3830", "Name": "Wellen", "Catchment": "Yes"},
      {"Code": "3831", "Name": "Wellen Herten", "Catchment": "Yes"},
      {"Code": "3832", "Name": "Wellen Ulbeek", "Catchment": "Yes"},
      {"Code": "3840", "Name": "Borgloon Kolmont", "Catchment": "Yes"},
      {"Code": "3850", "Name": "Nieuwerkerken", "Catchment": "Yes"},
      {"Code": "3870", "Name": "Heers Klein-Gelmen", "Catchment": "Yes"},
      {"Code": "3890", "Name": "Gingelom Nielbij-Sint-Truiden", "Catchment": "Yes"},
      {"Code": "3891", "Name": "Gingelom Muizen", "Catchment": "Yes"},
      {"Code": "3900", "Name": "Overpelt", "Catchment": "Yes"},
      {"Code": "3910", "Name": "Neerpelt Grote Heide", "Catchment": "Yes"},
      {"Code": "3920", "Name": "Lommel", "Catchment": "Yes"},
      {"Code": "3930", "Name": "Hamont-Achel", "Catchment": "Yes"},
      {"Code": "3940", "Name": "Hechtel-Eksel", "Catchment": "Yes"},
      {"Code": "3941", "Name": "Hechtel-Eksel", "Catchment": "Yes"},
      {"Code": "3945", "Name": "Ham Kwaadmechelen", "Catchment": "Yes"},
      {"Code": "3950", "Name": "Bocholt Kaulille", "Catchment": "Yes"},
      {"Code": "3960", "Name": "Bree Opitter, Tongerlo", "Catchment": "Yes"},
      {"Code": "3970", "Name": "Leopoldsburg", "Catchment": "Yes"},
      {"Code": "3971", "Name": "Leopoldsburg Heppen", "Catchment": "Yes"},
      {"Code": "3980", "Name": "Tessenderlo", "Catchment": "Yes"},
      {"Code": "3990", "Name": "Peer Kleine-Brogel", "Catchment": "Yes"},
      {"Code": "8000", "Name": "Brugge", "Catchment": "Yes"},
      {"Code": "8020", "Name": "Oostkamp", "Catchment": "Yes"},
      {"Code": "8200", "Name": "Brugge Sint-Michiels", "Catchment": "Yes"},
      {"Code": "8210", "Name": "Zedelgem", "Catchment": "Yes"},
      {"Code": "8211", "Name": "Zedelgem", "Catchment": "Yes"},
      {"Code": "8300", "Name": "Knokke-Heist Knokke", "Catchment": "Yes"},
      {"Code": "8301", "Name": "Knokke-Heist Ramskapelle", "Catchment": "Yes"},
      {"Code": "8310", "Name": "Brugge Sint-Kruis", "Catchment": "Yes"},
      {"Code": "8340", "Name": "Damme Moerkerke", "Catchment": "Yes"},
      {"Code": "8370", "Name": "Blankenberge Uitkerke", "Catchment": "Yes"},
      {"Code": "8377", "Name": "Zuienkerke Meetkerke", "Catchment": "Yes"},
      {"Code": "8380", "Name": "Brugge", "Catchment": "Yes"},
      {"Code": "8400", "Name": "Oostende Zandvoorde", "Catchment": "Yes"},
      {"Code": "8420", "Name": "De Haan De Haan", "Catchment": "Yes"},
      {"Code": "8421", "Name": "De Haan", "Catchment": "Yes"},
      {"Code": "8430", "Name": "Middelkerke", "Catchment": "Yes"},
      {"Code": "8431", "Name": "Middelkerke Wilskerke", "Catchment": "Yes"},
      {"Code": "8432", "Name": "Middelkerke Leffinge", "Catchment": "Yes"},
      {"Code": "8433", "Name": "Middelkerke Sint-Pieters-Kapelle", "Catchment": "Yes"},
      {"Code": "8434", "Name": "Middelkerke Lombardsijde", "Catchment": "Yes"},
      {"Code": "8450", "Name": "Bredene", "Catchment": "Yes"},
      {"Code": "8460", "Name": "Oudenburg Westkerke", "Catchment": "Yes"},
      {"Code": "8470", "Name": "Gistel Moere", "Catchment": "Yes"},
      {"Code": "8480", "Name": "Ichtegem Eernegem", "Catchment": "Yes"},
      {"Code": "8490", "Name": "Jabbeke Varsenare", "Catchment": "Yes"},
      {"Code": "8500", "Name": "Kortrijk", "Catchment": "Yes"},
      {"Code": "8501", "Name": "Kortrijk Heule", "Catchment": "Yes"},
      {"Code": "8510", "Name": "Kortrijk Marke", "Catchment": "Yes"},
      {"Code": "8511", "Name": "Kortrijk", "Catchment": "Yes"},
      {"Code": "8520", "Name": "Kuurne", "Catchment": "Yes"},
      {"Code": "8530", "Name": "Harelbeke", "Catchment": "Yes"},
      {"Code": "8531", "Name": "Harelbeke", "Catchment": "Yes"},
      {"Code": "8540", "Name": "Deerlijk", "Catchment": "Yes"},
      {"Code": "8550", "Name": "Zwevegem", "Catchment": "Yes"},
      {"Code": "8551", "Name": "Zwevegem Heestert", "Catchment": "Yes"},
      {"Code": "8552", "Name": "Zwevegem", "Catchment": "Yes"},
      {"Code": "8553", "Name": "Zwevegem Otegem", "Catchment": "Yes"},
      {"Code": "8554", "Name": "Zwevegem", "Catchment": "Yes"},
      {"Code": "8560", "Name": "Wevelgem Moorsele", "Catchment": "Yes"},
      {"Code": "8570", "Name": "Anzegem", "Catchment": "Yes"},
      {"Code": "8572", "Name": "Anzegem", "Catchment": "Yes"},
      {"Code": "8573", "Name": "Anzegem Tiegem", "Catchment": "Yes"},
      {"Code": "8580", "Name": "Avelgem", "Catchment": "Yes"},
      {"Code": "8581", "Name": "Avelgem", "Catchment": "Yes"},
      {"Code": "8582", "Name": "Avelgem Outrijve", "Catchment": "Yes"},
      {"Code": "8583", "Name": "Avelgem Bossuit", "Catchment": "Yes"},
      {"Code": "8587", "Name": "Spiere-Helkijn Spiere", "Catchment": "Yes"},
      {"Code": "8600", "Name": "Diksmuide Kaaskerke", "Catchment": "Yes"},
      {"Code": "8610", "Name": "Kortemark Zarren", "Catchment": "Yes"},
      {"Code": "8620", "Name": "Nieuwpoort Sint-Joris", "Catchment": "Yes"},
      {"Code": "8630", "Name": "Veurne Houtem", "Catchment": "Yes"},
      {"Code": "8640", "Name": "Vleteren Oostvleteren", "Catchment": "Yes"},
      {"Code": "8647", "Name": "Lo-Reninge Reninge", "Catchment": "Yes"},
      {"Code": "8650", "Name": "Houthulst Klerken", "Catchment": "Yes"},
      {"Code": "8660", "Name": "De Panne De Panne", "Catchment": "Yes"},
      {"Code": "8670", "Name": "Koksijde Sint-Idesbald", "Catchment": "Yes"},
      {"Code": "8680", "Name": "Koekelare Zande", "Catchment": "Yes"},
      {"Code": "8690", "Name": "Alveringem Hoogstade", "Catchment": "Yes"},
      {"Code": "8691", "Name": "Alveringem Beverenaanden-Ijzer", "Catchment": "Yes"},
      {"Code": "8700", "Name": "Tielt Kanegem", "Catchment": "Yes"},
      {"Code": "8710", "Name": "Wielsbeke Ooigem", "Catchment": "Yes"},
      {"Code": "8720", "Name": "Dentergem Wakken", "Catchment": "Yes"},
      {"Code": "8730", "Name": "Beernem", "Catchment": "Yes"},
      {"Code": "8740", "Name": "Pittem Egem", "Catchment": "Yes"},
      {"Code": "8750", "Name": "Wingene", "Catchment": "Yes"},
      {"Code": "8755", "Name": "Ruiselede", "Catchment": "Yes"},
      {"Code": "8760", "Name": "Meulebeke", "Catchment": "Yes"},
      {"Code": "8770", "Name": "Ingelmunster", "Catchment": "Yes"},
      {"Code": "8780", "Name": "Oostrozebeke", "Catchment": "Yes"},
      {"Code": "8790", "Name": "Waregem", "Catchment": "Yes"},
      {"Code": "8791", "Name": "Waregem Beveren", "Catchment": "Yes"},
      {"Code": "8792", "Name": "Waregem", "Catchment": "Yes"},
      {"Code": "8793", "Name": "Waregem Sint-Eloois-Vijve", "Catchment": "Yes"},
      {"Code": "8800", "Name": "Roeselare Beveren", "Catchment": "Yes"},
      {"Code": "8810", "Name": "Lichtervelde", "Catchment": "Yes"},
      {"Code": "8820", "Name": "Torhout", "Catchment": "Yes"},
      {"Code": "8830", "Name": "Hooglede", "Catchment": "Yes"},
      {"Code": "8840", "Name": "Staden Westrozebeke", "Catchment": "Yes"},
      {"Code": "8850", "Name": "Ardooie", "Catchment": "Yes"},
      {"Code": "8851", "Name": "Ardooie Koolskamp", "Catchment": "Yes"},
      {"Code": "8860", "Name": "Lendelede", "Catchment": "Yes"},
      {"Code": "8870", "Name": "Izegem", "Catchment": "Yes"},
      {"Code": "8880", "Name": "Ledegem Rollegem-Kapelle", "Catchment": "Yes"},
      {"Code": "8890", "Name": "Moorslede Dadizele", "Catchment": "Yes"},
      {"Code": "8900", "Name": "Ieper", "Catchment": "Yes"},
      {"Code": "8902", "Name": "Ieper Zillebeke", "Catchment": "Yes"},
      {"Code": "8904", "Name": "Ieper", "Catchment": "Yes"},
      {"Code": "8906", "Name": "Ieper Elverdinge", "Catchment": "Yes"},
      {"Code": "8908", "Name": "Ieper Vlamertinge", "Catchment": "Yes"},
      {"Code": "8920", "Name": "Langemark-Poelkapelle Poelkapelle", "Catchment": "Yes"},
      {"Code": "8930", "Name": "Menen", "Catchment": "Yes"},
      {"Code": "8940", "Name": "Wervik Geluwe", "Catchment": "Yes"},
      {"Code": "8950", "Name": "Heuvelland Nieuwkerke", "Catchment": "Yes"},
      {"Code": "8951", "Name": "Heuvelland", "Catchment": "Yes"},
      {"Code": "8952", "Name": "Heuvelland Wulvergem", "Catchment": "Yes"},
      {"Code": "8953", "Name": "Heuvelland Wijtschate", "Catchment": "Yes"},
      {"Code": "8954", "Name": "Heuvelland", "Catchment": "Yes"},
      {"Code": "8956", "Name": "Heuvelland Kemmel", "Catchment": "Yes"},
      {"Code": "8957", "Name": "Mesen", "Catchment": "Yes"},
      {"Code": "8958", "Name": "Heuvelland Loker", "Catchment": "Yes"},
      {"Code": "8970", "Name": "Poperinge", "Catchment": "Yes"},
      {"Code": "8972", "Name": "Poperinge Krombeke", "Catchment": "Yes"},
      {"Code": "8978", "Name": "Poperinge", "Catchment": "Yes"},
      {"Code": "8980", "Name": "Zonnebeke Beselare", "Catchment": "Yes"},
      {"Code": "9000", "Name": "Gent", "Catchment": "Yes"},
      {"Code": "9030", "Name": "Gent Mariakerke", "Catchment": "Yes"},
      {"Code": "9031", "Name": "Gent", "Catchment": "Yes"},
      {"Code": "9032", "Name": "Gent Wondelgem", "Catchment": "Yes"},
      {"Code": "9040", "Name": "Gent", "Catchment": "Yes"},
      {"Code": "9041", "Name": "Gent", "Catchment": "Yes"},
      {"Code": "9042", "Name": "Gent Mendonk", "Catchment": "Yes"},
      {"Code": "9050", "Name": "Gent Gentbrugge", "Catchment": "Yes"},
      {"Code": "9051", "Name": "Gent Sint-Denijs-Westrem", "Catchment": "Yes"},
      {"Code": "9052", "Name": "Gent", "Catchment": "Yes"},
      {"Code": "9060", "Name": "Zelzate", "Catchment": "Yes"},
      {"Code": "9070", "Name": "Destelbergen Heusden", "Catchment": "Yes"},
      {"Code": "9080", "Name": "Lochristi Zeveneken", "Catchment": "Yes"},
      {"Code": "9090", "Name": "Melle Gontrode", "Catchment": "Yes"},
      {"Code": "9100", "Name": "Sint-Niklaas Nieuwkerken-Waas", "Catchment": "Yes"},
      {"Code": "9111", "Name": "Sint-Niklaas Belsele", "Catchment": "Yes"},
      {"Code": "9112", "Name": "Sint-Niklaas", "Catchment": "Yes"},
      {"Code": "9120", "Name": "Beveren Kallo", "Catchment": "Yes"},
      {"Code": "9130", "Name": "Beveren", "Catchment": "Yes"},
      {"Code": "9140", "Name": "Temse Tielrode", "Catchment": "Yes"},
      {"Code": "9150", "Name": "Kruibeke Bazel", "Catchment": "Yes"},
      {"Code": "9160", "Name": "Lokeren Eksaarde", "Catchment": "Yes"},
      {"Code": "9170", "Name": "Sint-Gillis-Waas", "Catchment": "Yes"},
      {"Code": "9180", "Name": "Moerbeke-Waas", "Catchment": "Yes"},
      {"Code": "9185", "Name": "Wachtebeke", "Catchment": "Yes"},
      {"Code": "9190", "Name": "Stekene", "Catchment": "Yes"},
      {"Code": "9200", "Name": "Dendermonde Mespelare", "Catchment": "Yes"},
      {"Code": "9220", "Name": "Hamme", "Catchment": "Yes"},
      {"Code": "9230", "Name": "Wetteren Massemen", "Catchment": "Yes"},
      {"Code": "9240", "Name": "Zele", "Catchment": "Yes"},
      {"Code": "9250", "Name": "Waasmunster", "Catchment": "Yes"},
      {"Code": "9255", "Name": "Buggenhout Opstal", "Catchment": "Yes"},
      {"Code": "9260", "Name": "Wichelen Schellebelle", "Catchment": "Yes"},
      {"Code": "9270", "Name": "Laarne", "Catchment": "Yes"},
      {"Code": "9280", "Name": "Lebbeke Denderbelle", "Catchment": "Yes"},
      {"Code": "9290", "Name": "Berlare Overmere", "Catchment": "Yes"},
      {"Code": "9300", "Name": "Aalst", "Catchment": "Yes"},
      {"Code": "9308", "Name": "Aalst", "Catchment": "Yes"},
      {"Code": "9310", "Name": "Aalst Moorsel", "Catchment": "Yes"},
      {"Code": "9320", "Name": "Aalst Nieuwerkerken", "Catchment": "Yes"},
      {"Code": "9340", "Name": "Lede Wanzele", "Catchment": "Yes"},
      {"Code": "9400", "Name": "Ninove Nederhasselt", "Catchment": "Yes"},
      {"Code": "9401", "Name": "Ninove", "Catchment": "Yes"},
      {"Code": "9402", "Name": "Ninove Meerbeke", "Catchment": "Yes"},
      {"Code": "9403", "Name": "Ninove", "Catchment": "Yes"},
      {"Code": "9404", "Name": "Ninove Aspelare", "Catchment": "Yes"},
      {"Code": "9406", "Name": "Ninove Outer", "Catchment": "Yes"},
      {"Code": "9420", "Name": "Erpe-Mere Burst", "Catchment": "Yes"},
      {"Code": "9450", "Name": "Haaltert Denderhoutem", "Catchment": "Yes"},
      {"Code": "9451", "Name": "Haaltert", "Catchment": "Yes"},
      {"Code": "9470", "Name": "Denderleeuw", "Catchment": "Yes"},
      {"Code": "9472", "Name": "Denderleeuw", "Catchment": "Yes"},
      {"Code": "9473", "Name": "Denderleeuw Welle", "Catchment": "Yes"},
      {"Code": "9500", "Name": "Geraardsbergen Ophasselt", "Catchment": "Yes"},
      {"Code": "9506", "Name": "Geraardsbergen Waarbeke", "Catchment": "Yes"},
      {"Code": "9520", "Name": "Sint-Lievens-Houtem Bavegem", "Catchment": "Yes"},
      {"Code": "9521", "Name": "Sint-Lievens-Houtem Letterhoutem", "Catchment": "Yes"},
      {"Code": "9550", "Name": "Herzele Woubrechtegem", "Catchment": "Yes"},
      {"Code": "9551", "Name": "Herzele", "Catchment": "Yes"},
      {"Code": "9552", "Name": "Herzele", "Catchment": "Yes"},
      {"Code": "9570", "Name": "Lierde Deftinge", "Catchment": "Yes"},
      {"Code": "9571", "Name": "Lierde", "Catchment": "Yes"},
      {"Code": "9572", "Name": "Lierde", "Catchment": "Yes"},
      {"Code": "9600", "Name": "Ronse", "Catchment": "Yes"},
      {"Code": "9620", "Name": "Zottegem Strijpen", "Catchment": "Yes"},
      {"Code": "9630", "Name": "Zwalm Meilegem", "Catchment": "Yes"},
      {"Code": "9636", "Name": "Zwalm Hermelgem", "Catchment": "Yes"},
      {"Code": "9660", "Name": "Brakel Michelbeke", "Catchment": "Yes"},
      {"Code": "9661", "Name": "Brakel Parike", "Catchment": "Yes"},
      {"Code": "9667", "Name": "Horebeke Sint-Maria-Horebeke", "Catchment": "Yes"},
      {"Code": "9680", "Name": "Maarkedal Etikhove", "Catchment": "Yes"},
      {"Code": "9681", "Name": "Maarkedal Nukerke", "Catchment": "Yes"},
      {"Code": "9688", "Name": "Maarkedal Schorisse", "Catchment": "Yes"},
      {"Code": "9690", "Name": "Kluisbergen", "Catchment": "Yes"},
      {"Code": "9700", "Name": "Oudenaarde Melden", "Catchment": "Yes"},
      {"Code": "9750", "Name": "Zingem", "Catchment": "Yes"},
      {"Code": "9770", "Name": "Kruishoutem", "Catchment": "Yes"},
      {"Code": "9771", "Name": "Kruishoutem Nokere", "Catchment": "Yes"},
      {"Code": "9772", "Name": "Kruishoutem Wannegem-Lede", "Catchment": "Yes"},
      {"Code": "9790", "Name": "Wortegem-Petegem", "Catchment": "Yes"},
      {"Code": "9800", "Name": "Deinze Bachte-Maria-Leerne", "Catchment": "Yes"},
      {"Code": "9810", "Name": "Nazareth", "Catchment": "Yes"},
      {"Code": "9820", "Name": "Merelbeke", "Catchment": "Yes"},
      {"Code": "9830", "Name": "Sint-Martens-Latem", "Catchment": "Yes"},
      {"Code": "9831", "Name": "Sint-Martens-Latem Deurle", "Catchment": "Yes"},
      {"Code": "9840", "Name": "De Pinte Zevergem", "Catchment": "Yes"},
      {"Code": "9850", "Name": "Nevele Hansbeke", "Catchment": "Yes"},
      {"Code": "9860", "Name": "Oosterzele Scheldewindeke", "Catchment": "Yes"},
      {"Code": "9870", "Name": "Zulte Olsene", "Catchment": "Yes"},
      {"Code": "9880", "Name": "Aalter", "Catchment": "Yes"},
      {"Code": "9881", "Name": "Aalter Bellem", "Catchment": "Yes"},
      {"Code": "9890", "Name": "Gavere Semmerzake", "Catchment": "Yes"},
      {"Code": "9900", "Name": "Eeklo", "Catchment": "Yes"},
      {"Code": "9910", "Name": "Knesselare", "Catchment": "Yes"},
      {"Code": "9920", "Name": "Lovendegem", "Catchment": "Yes"},
      {"Code": "9921", "Name": "Lovendegem Vinderhoute", "Catchment": "Yes"},
      {"Code": "9930", "Name": "Zomergem", "Catchment": "Yes"},
      {"Code": "9931", "Name": "Zomergem Oostwinkel", "Catchment": "Yes"},
      {"Code": "9932", "Name": "Zomergem Ronsele", "Catchment": "Yes"},
      {"Code": "9940", "Name": "Evergem Sleidinge", "Catchment": "Yes"},
      {"Code": "9950", "Name": "Waarschoot", "Catchment": "Yes"},
      {"Code": "9960", "Name": "Assenede", "Catchment": "Yes"},
      {"Code": "9961", "Name": "Assenede Boekhoute", "Catchment": "Yes"},
      {"Code": "9968", "Name": "Assenede Oosteeklo", "Catchment": "Yes"},
      {"Code": "9970", "Name": "Kaprijke", "Catchment": "Yes"},
      {"Code": "9971", "Name": "Kaprijke", "Catchment": "Yes"},
      {"Code": "9980", "Name": "Sint-Laureins", "Catchment": "Yes"},
      {"Code": "9981", "Name": "Tienen Sint-Margriete-Houtem", "Catchment": "Yes"},
      {"Code": "9982", "Name": "Sint-Laureins Sint-Janin-Eremo", "Catchment": "Yes"},
      {"Code": "9988", "Name": "Sint-Laureins Watervliet", "Catchment": "Yes"},
      {"Code": "9990", "Name": "Maldegem", "Catchment": "Yes"},
      {"Code": "9991", "Name": "Maldegem Adegem", "Catchment": "Yes"},
      {"Code": "9992", "Name": "Maldegem Middelburg", "Catchment": "Yes"},
      {"Code": "1300", "Name": "Wavre Limal", "Catchment": "Yes"},
      {"Code": "1301", "Name": "Wavre Bierges", "Catchment": "Yes"},
      {"Code": "1310", "Name": "La Hulpe", "Catchment": "Yes"},
      {"Code": "1315", "Name": "Incourt Piètrebais", "Catchment": "Yes"},
      {"Code": "1320", "Name": "Beauvechain Nodebais", "Catchment": "Yes"},
      {"Code": "1325", "Name": "Chaumont-Gistoux Bonlez", "Catchment": "Yes"},
      {"Code": "1330", "Name": "Rixensart", "Catchment": "Yes"},
      {"Code": "1331", "Name": "Rixensart Rosières", "Catchment": "Yes"},
      {"Code": "1332", "Name": "Rixensart Genval", "Catchment": "Yes"},
      {"Code": "1340", "Name": "Ottignies-Louvainla-Neuve", "Catchment": "Yes"},
      {"Code": "1341", "Name": "Ottignies-Louvainla-Neuve Céroux-Mousty", "Catchment": "Yes"},
      {"Code": "1342", "Name": "Ottignies-Louvainla-Neuve Limelette", "Catchment": "Yes"},
      {"Code": "1348", "Name": "Ottignies-Louvainla-Neuve Louvainla-Neuve", "Catchment": "Yes"},
      {"Code": "1350", "Name": "Nivelles Noduwez", "Catchment": "Yes"},
      {"Code": "1357", "Name": "Florennes Linsmeau", "Catchment": "Yes"},
      {"Code": "1360", "Name": "Perwez Orbais", "Catchment": "Yes"},
      {"Code": "1367", "Name": "Ramillies Gérompont", "Catchment": "Yes"},
      {"Code": "1370", "Name": "Jodoigne Mélin", "Catchment": "Yes"},
      {"Code": "1380", "Name": "Lasne Lasne-Chapelle-Saint-Lambert", "Catchment": "Yes"},
      {"Code": "1390", "Name": "Grez-Doiceau Biez", "Catchment": "Yes"},
      {"Code": "1400", "Name": "Nivelles", "Catchment": "Yes"},
      {"Code": "1401", "Name": "Nivelles Baulers", "Catchment": "Yes"},
      {"Code": "1402", "Name": "Nivelles Thines", "Catchment": "Yes"},
      {"Code": "1404", "Name": "Nivelles Bornival", "Catchment": "Yes"},
      {"Code": "1410", "Name": "Waterloo", "Catchment": "Yes"},
      {"Code": "1414", "Name": "Promo-Control", "Catchment": "Yes"},
      {"Code": "1420", "Name": "Brainel'Alleud Brainel'Alleud", "Catchment": "Yes"},
      {"Code": "1421", "Name": "Brainel'Alleud Ophain-Bois-Seigneur-Isaac", "Catchment": "Yes"},
      {"Code": "1428", "Name": "Brainel'Alleud", "Catchment": "Yes"},
      {"Code": "1430", "Name": "Rebecq Quenast", "Catchment": "Yes"},
      {"Code": "1435", "Name": "Mont-Saint-Guibert", "Catchment": "Yes"},
      {"Code": "1440", "Name": "Brainele-Château Wauthier-Braine", "Catchment": "Yes"},
      {"Code": "1450", "Name": "Chastre Gentinnes", "Catchment": "Yes"},
      {"Code": "1457", "Name": "Walhain Nil-Saint-Vincent-Saint-Martin", "Catchment": "Yes"},
      {"Code": "1460", "Name": "Ittre Virginal-Samme", "Catchment": "Yes"},
      {"Code": "1461", "Name": "Ittre Haut-Ittre", "Catchment": "Yes"},
      {"Code": "1470", "Name": "Genappe Baisy-Thy", "Catchment": "Yes"},
      {"Code": "1471", "Name": "Genappe Loupoigne", "Catchment": "Yes"},
      {"Code": "1472", "Name": "Genappe Vieux-Genappe", "Catchment": "Yes"},
      {"Code": "1473", "Name": "Genappe Glabais", "Catchment": "Yes"},
      {"Code": "1474", "Name": "Genappe Ways", "Catchment": "Yes"},
      {"Code": "1476", "Name": "Genappe Houtainle-Val", "Catchment": "Yes"},
      {"Code": "1480", "Name": "Tubize", "Catchment": "Yes"},
      {"Code": "1490", "Name": "Court-Saint-Etienne", "Catchment": "Yes"},
      {"Code": "1495", "Name": "Villersla-Ville Marbais", "Catchment": "Yes"},
      {"Code": "4000", "Name": "Liège", "Catchment": "Yes"},
      {"Code": "4020", "Name": "Liège Wandre", "Catchment": "Yes"},
      {"Code": "4030", "Name": "Liège Grivegnée", "Catchment": "Yes"},
      {"Code": "4031", "Name": "Liège Angleur", "Catchment": "Yes"},
      {"Code": "4032", "Name": "Liège Chênée", "Catchment": "Yes"},
      {"Code": "4040", "Name": "Herstal", "Catchment": "Yes"},
      {"Code": "4041", "Name": "Herstal Milmort", "Catchment": "Yes"},
      {"Code": "4042", "Name": "Herstal", "Catchment": "Yes"},
      {"Code": "4050", "Name": "Chaudfontaine", "Catchment": "Yes"},
      {"Code": "4051", "Name": "Chaudfontaine Vauxsous-Chèvremont", "Catchment": "Yes"},
      {"Code": "4052", "Name": "Chaudfontaine", "Catchment": "Yes"},
      {"Code": "4053", "Name": "Chaudfontaine", "Catchment": "Yes"},
      {"Code": "4100", "Name": "Seraing Boncelles", "Catchment": "Yes"},
      {"Code": "4101", "Name": "Seraing Jemeppesur-Meuse", "Catchment": "Yes"},
      {"Code": "4102", "Name": "Seraing Ougrée", "Catchment": "Yes"},
      {"Code": "4120", "Name": "Neupré Ehein", "Catchment": "Yes"},
      {"Code": "4121", "Name": "Neupré Neuvilleen-Condroz", "Catchment": "Yes"},
      {"Code": "4122", "Name": "Neupré Plainevaux", "Catchment": "Yes"},
      {"Code": "4130", "Name": "Esneux Tilff", "Catchment": "Yes"},
      {"Code": "4140", "Name": "Sprimont Gomze-Andoumont", "Catchment": "Yes"},
      {"Code": "4141", "Name": "Sprimont Louveigné", "Catchment": "Yes"},
      {"Code": "4151", "Name": "Anthisnes", "Catchment": "Yes"},
      {"Code": "4160", "Name": "Anthisnes", "Catchment": "Yes"},
      {"Code": "4161", "Name": "Anthisnes Villersaux-Tours", "Catchment": "Yes"},
      {"Code": "4162", "Name": "Anthisnes", "Catchment": "Yes"},
      {"Code": "4163", "Name": "Anthisnes Tavier", "Catchment": "Yes"},
      {"Code": "4170", "Name": "Comblainau-Pont", "Catchment": "Yes"},
      {"Code": "4171", "Name": "Comblainau-Pont Poulseur", "Catchment": "Yes"},
      {"Code": "4180", "Name": "Hamoir Comblain-Fairon", "Catchment": "Yes"},
      {"Code": "4181", "Name": "Hamoir", "Catchment": "Yes"},
      {"Code": "4190", "Name": "Ferrières Xhoris", "Catchment": "Yes"},
      {"Code": "4210", "Name": "Burdinne Lamontzée", "Catchment": "Yes"},
      {"Code": "4217", "Name": "Héron Waretl'Evêque", "Catchment": "Yes"},
      {"Code": "4218", "Name": "Héron Couthuin", "Catchment": "Yes"},
      {"Code": "4219", "Name": "Wasseiges", "Catchment": "Yes"},
      {"Code": "4250", "Name": "Geer Hollognesur-Geer", "Catchment": "Yes"},
      {"Code": "4252", "Name": "Geer Omal", "Catchment": "Yes"},
      {"Code": "4253", "Name": "Geer", "Catchment": "Yes"},
      {"Code": "4254", "Name": "Geer Ligney", "Catchment": "Yes"},
      {"Code": "4257", "Name": "Berloz", "Catchment": "Yes"},
      {"Code": "4260", "Name": "Braives Fallais", "Catchment": "Yes"},
      {"Code": "4261", "Name": "Braives Latinne", "Catchment": "Yes"},
      {"Code": "4263", "Name": "Braives Tourinne", "Catchment": "Yes"},
      {"Code": "4280", "Name": "Hannut", "Catchment": "Yes"},
      {"Code": "4287", "Name": "Lincent Pellaines", "Catchment": "Yes"},
      {"Code": "4300", "Name": "Waremme Oleye", "Catchment": "Yes"},
      {"Code": "4317", "Name": "Faimes Celles", "Catchment": "Yes"},
      {"Code": "4340", "Name": "Awans Othée", "Catchment": "Yes"},
      {"Code": "4342", "Name": "Awans Hognoul", "Catchment": "Yes"},
      {"Code": "4347", "Name": "Fexhele-Haut-Clocher Voroux-Goreux", "Catchment": "Yes"},
      {"Code": "4350", "Name": "Remicourt Momalle", "Catchment": "Yes"},
      {"Code": "4351", "Name": "Remicourt Hodeige", "Catchment": "Yes"},
      {"Code": "4357", "Name": "Donceel Haneffe", "Catchment": "Yes"},
      {"Code": "4360", "Name": "Oreye", "Catchment": "Yes"},
      {"Code": "4367", "Name": "Crisnée", "Catchment": "Yes"},
      {"Code": "4400", "Name": "Flémalle Monslez-Liège", "Catchment": "Yes"},
      {"Code": "4420", "Name": "Saint-Nicolas Tilleur", "Catchment": "Yes"},
      {"Code": "4430", "Name": "Ans", "Catchment": "Yes"},
      {"Code": "4431", "Name": "Ans", "Catchment": "Yes"},
      {"Code": "4432", "Name": "Ans Alleur", "Catchment": "Yes"},
      {"Code": "4450", "Name": "Juprelle Slins", "Catchment": "Yes"},
      {"Code": "4451", "Name": "Juprelle", "Catchment": "Yes"},
      {"Code": "4452", "Name": "Juprelle Paifve", "Catchment": "Yes"},
      {"Code": "4453", "Name": "Juprelle", "Catchment": "Yes"},
      {"Code": "4458", "Name": "Juprelle Fexhe-Slins", "Catchment": "Yes"},
      {"Code": "4460", "Name": "Grâce-Hollogne Horion-Hozémont", "Catchment": "Yes"},
      {"Code": "4470", "Name": "Saint-Georgessur-Meuse", "Catchment": "Yes"},
      {"Code": "4480", "Name": "Engis Hermallesous-Huy", "Catchment": "Yes"},
      {"Code": "4500", "Name": "Huy Ben-Ahin", "Catchment": "Yes"},
      {"Code": "4520", "Name": "Wanze Bas-Oha", "Catchment": "Yes"},
      {"Code": "4530", "Name": "Villersle-Bouillet Vieux-Waleffe", "Catchment": "Yes"},
      {"Code": "4537", "Name": "Verlaine", "Catchment": "Yes"},
      {"Code": "4540", "Name": "Amay", "Catchment": "Yes"},
      {"Code": "4550", "Name": "Nandrin Villersle-Temple", "Catchment": "Yes"},
      {"Code": "4557", "Name": "Tinlot Ramelot", "Catchment": "Yes"},
      {"Code": "4560", "Name": "Clavier Terwagne", "Catchment": "Yes"},
      {"Code": "4570", "Name": "Marchin", "Catchment": "Yes"},
      {"Code": "4577", "Name": "Modave Vierset-Barse", "Catchment": "Yes"},
      {"Code": "4590", "Name": "Ouffet Warzée", "Catchment": "Yes"},
      {"Code": "4600", "Name": "Visé Lixhe", "Catchment": "Yes"},
      {"Code": "4601", "Name": "Visé Argenteau", "Catchment": "Yes"},
      {"Code": "4602", "Name": "Visé", "Catchment": "Yes"},
      {"Code": "4606", "Name": "Dalhem", "Catchment": "Yes"},
      {"Code": "4607", "Name": "Dalhem Bombaye", "Catchment": "Yes"},
      {"Code": "4608", "Name": "Dalhem", "Catchment": "Yes"},
      {"Code": "4610", "Name": "Beyne-Heusay", "Catchment": "Yes"},
      {"Code": "4620", "Name": "Fléron", "Catchment": "Yes"},
      {"Code": "4621", "Name": "Fléron Retinne", "Catchment": "Yes"},
      {"Code": "4623", "Name": "Fléron Magnée", "Catchment": "Yes"},
      {"Code": "4624", "Name": "Fléron", "Catchment": "Yes"},
      {"Code": "4630", "Name": "Soumagne", "Catchment": "Yes"},
      {"Code": "4631", "Name": "Soumagne Evegnée", "Catchment": "Yes"},
      {"Code": "4632", "Name": "Soumagne", "Catchment": "Yes"},
      {"Code": "4633", "Name": "Soumagne", "Catchment": "Yes"},
      {"Code": "4650", "Name": "Herve", "Catchment": "Yes"},
      {"Code": "4651", "Name": "Herve", "Catchment": "Yes"},
      {"Code": "4652", "Name": "Herve Xhendelesse", "Catchment": "Yes"},
      {"Code": "4653", "Name": "Herve", "Catchment": "Yes"},
      {"Code": "4654", "Name": "Herve", "Catchment": "Yes"},
      {"Code": "4670", "Name": "Blégny", "Catchment": "Yes"},
      {"Code": "4671", "Name": "Blégny Housse", "Catchment": "Yes"},
      {"Code": "4672", "Name": "Blégny Saint-Remy", "Catchment": "Yes"},
      {"Code": "4680", "Name": "Oupeye Hermée", "Catchment": "Yes"},
      {"Code": "4681", "Name": "Oupeye Hermallesous-Argenteau", "Catchment": "Yes"},
      {"Code": "4682", "Name": "Oupeye Heurele-Romain", "Catchment": "Yes"},
      {"Code": "4683", "Name": "Oupeye Vivegnis", "Catchment": "Yes"},
      {"Code": "4684", "Name": "Oupeye Haccourt", "Catchment": "Yes"},
      {"Code": "4690", "Name": "Bassenge Boirs", "Catchment": "Yes"},
      {"Code": "4700", "Name": "Eupen", "Catchment": "Yes"},
      {"Code": "4701", "Name": "Eupen", "Catchment": "Yes"},
      {"Code": "4710", "Name": "Lontzen", "Catchment": "Yes"},
      {"Code": "4711", "Name": "Lontzen", "Catchment": "Yes"},
      {"Code": "4720", "Name": "Kelmis", "Catchment": "Yes"},
      {"Code": "4721", "Name": "Kelmis", "Catchment": "Yes"},
      {"Code": "4728", "Name": "Kelmis Hergenrath", "Catchment": "Yes"},
      {"Code": "4730", "Name": "Raeren", "Catchment": "Yes"},
      {"Code": "4731", "Name": "Raeren", "Catchment": "Yes"},
      {"Code": "4750", "Name": "Bütgenbach Elsenborn", "Catchment": "Yes"},
      {"Code": "4760", "Name": "Büllingen Manderfeld", "Catchment": "Yes"},
      {"Code": "4761", "Name": "Büllingen Rocherath", "Catchment": "Yes"},
      {"Code": "4770", "Name": "Amel Meyrode", "Catchment": "Yes"},
      {"Code": "4771", "Name": "Amel", "Catchment": "Yes"},
      {"Code": "4780", "Name": "Sankt Vith Sankt Vith", "Catchment": "Yes"},
      {"Code": "4782", "Name": "Sankt Vith Schönberg", "Catchment": "Yes"},
      {"Code": "4783", "Name": "Sankt Vith Lommersweiler", "Catchment": "Yes"},
      {"Code": "4784", "Name": "Sankt Vith", "Catchment": "Yes"},
      {"Code": "4790", "Name": "Burg-Reuland", "Catchment": "Yes"},
      {"Code": "4791", "Name": "Burg-Reuland Thommen", "Catchment": "Yes"},
      {"Code": "4800", "Name": "Verviers Lambermont", "Catchment": "Yes"},
      {"Code": "4801", "Name": "Verviers Stembert", "Catchment": "Yes"},
      {"Code": "4802", "Name": "Verviers Heusy", "Catchment": "Yes"},
      {"Code": "4820", "Name": "Dison", "Catchment": "Yes"},
      {"Code": "4821", "Name": "Dison Andrimont", "Catchment": "Yes"},
      {"Code": "4830", "Name": "Limbourg", "Catchment": "Yes"},
      {"Code": "4831", "Name": "Limbourg", "Catchment": "Yes"},
      {"Code": "4834", "Name": "Limbourg", "Catchment": "Yes"},
      {"Code": "4837", "Name": "Baelen Membach", "Catchment": "Yes"},
      {"Code": "4840", "Name": "Welkenraedt", "Catchment": "Yes"},
      {"Code": "4841", "Name": "Welkenraedt Henri-Chapelle", "Catchment": "Yes"},
      {"Code": "4845", "Name": "Jalhay", "Catchment": "Yes"},
      {"Code": "4850", "Name": "Plombières", "Catchment": "Yes"},
      {"Code": "4851", "Name": "Plombières Sippenaeken", "Catchment": "Yes"},
      {"Code": "4852", "Name": "Plombières", "Catchment": "Yes"},
      {"Code": "4860", "Name": "Pepinster", "Catchment": "Yes"},
      {"Code": "4861", "Name": "Pepinster", "Catchment": "Yes"},
      {"Code": "4870", "Name": "Trooz Nessonvaux", "Catchment": "Yes"},
      {"Code": "4877", "Name": "Olne", "Catchment": "Yes"},
      {"Code": "4880", "Name": "Aubel", "Catchment": "Yes"},
      {"Code": "4890", "Name": "Thimister-Clermont", "Catchment": "Yes"},
      {"Code": "4900", "Name": "Spa", "Catchment": "Yes"},
      {"Code": "4910", "Name": "Theux", "Catchment": "Yes"},
      {"Code": "4920", "Name": "Aywaille", "Catchment": "Yes"},
      {"Code": "4950", "Name": "Waimes Sourbrodt", "Catchment": "Yes"},
      {"Code": "4960", "Name": "Malmedy Bellevaux-Ligneuville", "Catchment": "Yes"},
      {"Code": "4970", "Name": "Stavelot Coo", "Catchment": "Yes"},
      {"Code": "4980", "Name": "Trois-Ponts", "Catchment": "Yes"},
      {"Code": "4983", "Name": "Trois-Ponts", "Catchment": "Yes"},
      {"Code": "4987", "Name": "Stoumont Cheneux", "Catchment": "Yes"},
      {"Code": "4990", "Name": "Lierneux Bra", "Catchment": "Yes"},
      {"Code": "5000", "Name": "Namur Beez", "Catchment": "Yes"},
      {"Code": "5001", "Name": "Namur", "Catchment": "Yes"},
      {"Code": "5002", "Name": "Namur Saint-Servais", "Catchment": "Yes"},
      {"Code": "5003", "Name": "Namur", "Catchment": "Yes"},
      {"Code": "5004", "Name": "Namur", "Catchment": "Yes"},
      {"Code": "5020", "Name": "Namur", "Catchment": "Yes"},
      {"Code": "5021", "Name": "Namur", "Catchment": "Yes"},
      {"Code": "5022", "Name": "Namur Cognelée", "Catchment": "Yes"},
      {"Code": "5024", "Name": "Namur Gelbressée", "Catchment": "Yes"},
      {"Code": "5030", "Name": "Gembloux Grand-Manil", "Catchment": "Yes"},
      {"Code": "5031", "Name": "Gembloux", "Catchment": "Yes"},
      {"Code": "5032", "Name": "Gembloux", "Catchment": "Yes"},
      {"Code": "5060", "Name": "Sambreville Falisolle", "Catchment": "Yes"},
      {"Code": "5070", "Name": "Fossesla-Ville", "Catchment": "Yes"},
      {"Code": "5080", "Name": "La Bruyère Rhisnes", "Catchment": "Yes"},
      {"Code": "5081", "Name": "La Bruyère Saint-Denis-Bovesse", "Catchment": "Yes"},
      {"Code": "5100", "Name": "Namur Naninne", "Catchment": "Yes"},
      {"Code": "5101", "Name": "Namur Livessur-Meuse", "Catchment": "Yes"},
      {"Code": "5140", "Name": "Sombreffe", "Catchment": "Yes"},
      {"Code": "5150", "Name": "Floreffe", "Catchment": "Yes"},
      {"Code": "5170", "Name": "Profondeville Arbre", "Catchment": "Yes"},
      {"Code": "5190", "Name": "Jemeppesur-Sambre Spy", "Catchment": "Yes"},
      {"Code": "5300", "Name": "Andenne Sclayn", "Catchment": "Yes"},
      {"Code": "5310", "Name": "Eghezée Branchon", "Catchment": "Yes"},
      {"Code": "5330", "Name": "Assesse Sart-Bernard", "Catchment": "Yes"},
      {"Code": "5332", "Name": "Assesse Crupet", "Catchment": "Yes"},
      {"Code": "5333", "Name": "Assesse Sorinnela-Longue", "Catchment": "Yes"},
      {"Code": "5334", "Name": "Assesse", "Catchment": "Yes"},
      {"Code": "5336", "Name": "Assesse", "Catchment": "Yes"},
      {"Code": "5340", "Name": "Gesves Haltinne", "Catchment": "Yes"},
      {"Code": "5350", "Name": "Ohey", "Catchment": "Yes"},
      {"Code": "5351", "Name": "Ohey Haillot", "Catchment": "Yes"},
      {"Code": "5352", "Name": "Ohey Perwez", "Catchment": "Yes"},
      {"Code": "5353", "Name": "Ohey", "Catchment": "Yes"},
      {"Code": "5354", "Name": "Ohey", "Catchment": "Yes"},
      {"Code": "5360", "Name": "Hamois", "Catchment": "Yes"},
      {"Code": "5361", "Name": "Hamois Mohiville", "Catchment": "Yes"},
      {"Code": "5362", "Name": "Hamois", "Catchment": "Yes"},
      {"Code": "5363", "Name": "Hamois", "Catchment": "Yes"},
      {"Code": "5364", "Name": "Hamois Schaltin", "Catchment": "Yes"},
      {"Code": "5370", "Name": "Havelange Porcheresse", "Catchment": "Yes"},
      {"Code": "5372", "Name": "Havelange", "Catchment": "Yes"},
      {"Code": "5374", "Name": "Havelange", "Catchment": "Yes"},
      {"Code": "5376", "Name": "Havelange Miécret", "Catchment": "Yes"},
      {"Code": "5377", "Name": "Somme-Leuze Waillet", "Catchment": "Yes"},
      {"Code": "5380", "Name": "Fernelmont Bierwart", "Catchment": "Yes"},
      {"Code": "5500", "Name": "Dinant", "Catchment": "Yes"},
      {"Code": "5501", "Name": "Dinant", "Catchment": "Yes"},
      {"Code": "5502", "Name": "Dinant Thynes", "Catchment": "Yes"},
      {"Code": "5503", "Name": "Dinant", "Catchment": "Yes"},
      {"Code": "5504", "Name": "Dinant", "Catchment": "Yes"},
      {"Code": "5520", "Name": "Onhaye Anthée", "Catchment": "Yes"},
      {"Code": "5521", "Name": "Onhaye", "Catchment": "Yes"},
      {"Code": "5522", "Name": "Onhaye", "Catchment": "Yes"},
      {"Code": "5523", "Name": "Onhaye Weillen", "Catchment": "Yes"},
      {"Code": "5524", "Name": "Onhaye", "Catchment": "Yes"},
      {"Code": "5530", "Name": "Yvoir Dorinne", "Catchment": "Yes"},
      {"Code": "5537", "Name": "Anhée Hautle-Wastia", "Catchment": "Yes"},
      {"Code": "5540", "Name": "Hastière Hastière-Lavaux", "Catchment": "Yes"},
      {"Code": "5541", "Name": "Hastière", "Catchment": "Yes"},
      {"Code": "5542", "Name": "Hastière Blaimont", "Catchment": "Yes"},
      {"Code": "5543", "Name": "Hastière Heer", "Catchment": "Yes"},
      {"Code": "5544", "Name": "Hastière Agimont", "Catchment": "Yes"},
      {"Code": "5550", "Name": "Vressesur-Semois Mouzaive", "Catchment": "Yes"},
      {"Code": "5555", "Name": "Bièvre Cornimont", "Catchment": "Yes"},
      {"Code": "5560", "Name": "Houyet Ciergnon", "Catchment": "Yes"},
      {"Code": "5561", "Name": "Houyet Celles", "Catchment": "Yes"},
      {"Code": "5562", "Name": "Houyet", "Catchment": "Yes"},
      {"Code": "5563", "Name": "Houyet Hour", "Catchment": "Yes"},
      {"Code": "5564", "Name": "Houyet Wanlin", "Catchment": "Yes"},
      {"Code": "5570", "Name": "Beauraing Dion", "Catchment": "Yes"},
      {"Code": "5571", "Name": "Beauraing", "Catchment": "Yes"},
      {"Code": "5572", "Name": "Beauraing", "Catchment": "Yes"},
      {"Code": "5573", "Name": "Beauraing Martouzin-Neuville", "Catchment": "Yes"},
      {"Code": "5574", "Name": "Beauraing Pondrôme", "Catchment": "Yes"},
      {"Code": "5575", "Name": "Gedinne Sart-Custinne", "Catchment": "Yes"},
      {"Code": "5576", "Name": "Beauraing Froidfontaine", "Catchment": "Yes"},
      {"Code": "5580", "Name": "Rochefort Eprave", "Catchment": "Yes"},
      {"Code": "5590", "Name": "Ciney Chevetogne", "Catchment": "Yes"},
      {"Code": "5600", "Name": "Philippeville Samart", "Catchment": "Yes"},
      {"Code": "5620", "Name": "Florennes Morville", "Catchment": "Yes"},
      {"Code": "5621", "Name": "Florennes Hanzinelle", "Catchment": "Yes"},
      {"Code": "5630", "Name": "Cerfontaine Soumoy", "Catchment": "Yes"},
      {"Code": "5640", "Name": "Mettet Oret", "Catchment": "Yes"},
      {"Code": "5641", "Name": "Mettet", "Catchment": "Yes"},
      {"Code": "5644", "Name": "Mettet Ermetonsur-Biert", "Catchment": "Yes"},
      {"Code": "5646", "Name": "Mettet Stave", "Catchment": "Yes"},
      {"Code": "5650", "Name": "Walcourt Clermont", "Catchment": "Yes"},
      {"Code": "5651", "Name": "Walcourt Rognée", "Catchment": "Yes"},
      {"Code": "5660", "Name": "Couvin Culdes-Sarts", "Catchment": "Yes"},
      {"Code": "5670", "Name": "Viroinval", "Catchment": "Yes"},
      {"Code": "5680", "Name": "Doische Matagnela-Grande", "Catchment": "Yes"},
      {"Code": "6000", "Name": "Charleroi", "Catchment": "Yes"},
      {"Code": "6001", "Name": "Charleroi", "Catchment": "Yes"},
      {"Code": "6010", "Name": "Charleroi Couillet", "Catchment": "Yes"},
      {"Code": "6020", "Name": "Charleroi", "Catchment": "Yes"},
      {"Code": "6030", "Name": "Charleroi", "Catchment": "Yes"},
      {"Code": "6031", "Name": "Charleroi", "Catchment": "Yes"},
      {"Code": "6032", "Name": "Charleroi Montsur-Marchienne", "Catchment": "Yes"},
      {"Code": "6040", "Name": "Charleroi", "Catchment": "Yes"},
      {"Code": "6041", "Name": "Charleroi Gosselies", "Catchment": "Yes"},
      {"Code": "6042", "Name": "Charleroi Lodelinsart", "Catchment": "Yes"},
      {"Code": "6043", "Name": "Charleroi Ransart", "Catchment": "Yes"},
      {"Code": "6044", "Name": "Charleroi", "Catchment": "Yes"},
      {"Code": "6060", "Name": "Charleroi", "Catchment": "Yes"},
      {"Code": "6061", "Name": "Charleroi", "Catchment": "Yes"},
      {"Code": "6110", "Name": "Montignyle-Tilleul", "Catchment": "Yes"},
      {"Code": "6111", "Name": "Montignyle-Tilleul Landelies", "Catchment": "Yes"},
      {"Code": "6120", "Name": "Hamsur-Heure-Nalinnes", "Catchment": "Yes"},
      {"Code": "6140", "Name": "Fontainel'Evêque", "Catchment": "Yes"},
      {"Code": "6141", "Name": "Fontainel'Evêque Forchiesla-Marche", "Catchment": "Yes"},
      {"Code": "6142", "Name": "Fontainel'Evêque", "Catchment": "Yes"},
      {"Code": "6150", "Name": "Anderlues", "Catchment": "Yes"},
      {"Code": "6180", "Name": "Courcelles", "Catchment": "Yes"},
      {"Code": "6181", "Name": "Courcelles", "Catchment": "Yes"},
      {"Code": "6182", "Name": "Courcelles Souvret", "Catchment": "Yes"},
      {"Code": "6183", "Name": "Courcelles Trazegnies", "Catchment": "Yes"},
      {"Code": "6200", "Name": "Châtelet Châtelineau", "Catchment": "Yes"},
      {"Code": "6210", "Name": "Les Bons Villers Frasneslez-Gosselies", "Catchment": "Yes"},
      {"Code": "6211", "Name": "Les Bons Villers", "Catchment": "Yes"},
      {"Code": "6220", "Name": "Fleurus Lambusart", "Catchment": "Yes"},
      {"Code": "6221", "Name": "Fleurus", "Catchment": "Yes"},
      {"Code": "6222", "Name": "Fleurus", "Catchment": "Yes"},
      {"Code": "6223", "Name": "Fleurus", "Catchment": "Yes"},
      {"Code": "6224", "Name": "Fleurus", "Catchment": "Yes"},
      {"Code": "6230", "Name": "Pontà-Celles Viesville", "Catchment": "Yes"},
      {"Code": "6238", "Name": "Pontà-Celles", "Catchment": "Yes"},
      {"Code": "6240", "Name": "Farciennes", "Catchment": "Yes"},
      {"Code": "6250", "Name": "Aiseau-Presles Roselies", "Catchment": "Yes"},
      {"Code": "6280", "Name": "Gerpinnes Loverval", "Catchment": "Yes"},
      {"Code": "6440", "Name": "Froidchapelle Boussulez-Walcourt", "Catchment": "Yes"},
      {"Code": "6441", "Name": "Froidchapelle Erpion", "Catchment": "Yes"},
      {"Code": "6460", "Name": "Chimay Villersla-Tour", "Catchment": "Yes"},
      {"Code": "6461", "Name": "Chimay", "Catchment": "Yes"},
      {"Code": "6462", "Name": "Chimay", "Catchment": "Yes"},
      {"Code": "6463", "Name": "Chimay", "Catchment": "Yes"},
      {"Code": "6464", "Name": "Chimay", "Catchment": "Yes"},
      {"Code": "6470", "Name": "Sivry-Rance Montbliart", "Catchment": "Yes"},
      {"Code": "6500", "Name": "Beaumont Barbençon", "Catchment": "Yes"},
      {"Code": "6511", "Name": "Beaumont Strée", "Catchment": "Yes"},
      {"Code": "6530", "Name": "Thuin Leerset-Fosteau", "Catchment": "Yes"},
      {"Code": "6531", "Name": "Thuin Biesmesous-Thuin", "Catchment": "Yes"},
      {"Code": "6532", "Name": "Thuin Ragnies", "Catchment": "Yes"},
      {"Code": "6533", "Name": "Thuin", "Catchment": "Yes"},
      {"Code": "6534", "Name": "Thuin Gozée", "Catchment": "Yes"},
      {"Code": "6536", "Name": "Thuin Thuillies", "Catchment": "Yes"},
      {"Code": "6540", "Name": "Lobbes Mont-Sainte-Geneviève", "Catchment": "Yes"},
      {"Code": "6542", "Name": "Lobbes Sarsla-Buissière", "Catchment": "Yes"},
      {"Code": "6543", "Name": "Lobbes Biennelez-Happart", "Catchment": "Yes"},
      {"Code": "6560", "Name": "Erquelinnes Grand-Reng", "Catchment": "Yes"},
      {"Code": "6567", "Name": "Merbesle-Château Labuissière", "Catchment": "Yes"},
      {"Code": "6590", "Name": "Momignies", "Catchment": "Yes"},
      {"Code": "6591", "Name": "Momignies", "Catchment": "Yes"},
      {"Code": "6592", "Name": "Momignies Monceau-Imbrechies", "Catchment": "Yes"},
      {"Code": "6593", "Name": "Momignies Macquenoise", "Catchment": "Yes"},
      {"Code": "6594", "Name": "Momignies Beauwelz", "Catchment": "Yes"},
      {"Code": "6596", "Name": "Momignies Forge-Philippe", "Catchment": "Yes"},
      {"Code": "6600", "Name": "Bastogne", "Catchment": "Yes"},
      {"Code": "6630", "Name": "Martelange", "Catchment": "Yes"},
      {"Code": "6637", "Name": "Fauvillers", "Catchment": "Yes"},
      {"Code": "6640", "Name": "Vaux-sur-Sûre Hompré", "Catchment": "Yes"},
      {"Code": "6642", "Name": "Juseret", "Catchment": "Yes"},
      {"Code": "6660", "Name": "Houffalize", "Catchment": "Yes"},
      {"Code": "6661", "Name": "Houffalize Mont", "Catchment": "Yes"},
      {"Code": "6662", "Name": "Houffalize Tavigny", "Catchment": "Yes"},
      {"Code": "6663", "Name": "Houffalize Mabompré", "Catchment": "Yes"},
      {"Code": "6666", "Name": "Houffalize Wibrin", "Catchment": "Yes"},
      {"Code": "6670", "Name": "Gouvy", "Catchment": "Yes"},
      {"Code": "6671", "Name": "Gouvy", "Catchment": "Yes"},
      {"Code": "6672", "Name": "Gouvy Beho", "Catchment": "Yes"},
      {"Code": "6673", "Name": "Gouvy Cherain", "Catchment": "Yes"},
      {"Code": "6674", "Name": "Gouvy", "Catchment": "Yes"},
      {"Code": "6680", "Name": "Sainte-Ode Tillet", "Catchment": "Yes"},
      {"Code": "6681", "Name": "Sainte-Ode", "Catchment": "Yes"},
      {"Code": "6686", "Name": "Bertogne Flamierge", "Catchment": "Yes"},
      {"Code": "6687", "Name": "Bertogne", "Catchment": "Yes"},
      {"Code": "6688", "Name": "Bertogne Longchamps", "Catchment": "Yes"},
      {"Code": "6690", "Name": "Vielsalm", "Catchment": "Yes"},
      {"Code": "6692", "Name": "Vielsalm", "Catchment": "Yes"},
      {"Code": "6698", "Name": "Vielsalm", "Catchment": "Yes"},
      {"Code": "6700", "Name": "Arlon Toernich", "Catchment": "Yes"},
      {"Code": "6704", "Name": "Arlon Guirsch", "Catchment": "Yes"},
      {"Code": "6706", "Name": "Arlon Autelbas", "Catchment": "Yes"},
      {"Code": "6717", "Name": "Attert Nobressart", "Catchment": "Yes"},
      {"Code": "6720", "Name": "Habay Habayla-Neuve", "Catchment": "Yes"},
      {"Code": "6721", "Name": "Habay", "Catchment": "Yes"},
      {"Code": "6723", "Name": "Habay Habayla-Vieille", "Catchment": "Yes"},
      {"Code": "6724", "Name": "Habay Marbehan", "Catchment": "Yes"},
      {"Code": "6730", "Name": "Tintigny Rossignol", "Catchment": "Yes"},
      {"Code": "6740", "Name": "Etalle", "Catchment": "Yes"},
      {"Code": "6741", "Name": "Etalle", "Catchment": "Yes"},
      {"Code": "6742", "Name": "Etalle", "Catchment": "Yes"},
      {"Code": "6743", "Name": "Etalle", "Catchment": "Yes"},
      {"Code": "6747", "Name": "Saint-Léger Meixle-Tige", "Catchment": "Yes"},
      {"Code": "6750", "Name": "Musson Signeulx", "Catchment": "Yes"},
      {"Code": "6760", "Name": "Virton Ruette", "Catchment": "Yes"},
      {"Code": "6761", "Name": "Virton", "Catchment": "Yes"},
      {"Code": "6762", "Name": "Virton Saint-Mard", "Catchment": "Yes"},
      {"Code": "6767", "Name": "Rouvroy Harnoncourt", "Catchment": "Yes"},
      {"Code": "6769", "Name": "Meixdevant-Virton Robelmont", "Catchment": "Yes"},
      {"Code": "6780", "Name": "Messancy Hondelange", "Catchment": "Yes"},
      {"Code": "6781", "Name": "Messancy", "Catchment": "Yes"},
      {"Code": "6782", "Name": "Messancy Habergy", "Catchment": "Yes"},
      {"Code": "6790", "Name": "Aubange", "Catchment": "Yes"},
      {"Code": "6791", "Name": "Aubange", "Catchment": "Yes"},
      {"Code": "6792", "Name": "Aubange", "Catchment": "Yes"},
      {"Code": "6800", "Name": "Libramont-Chevigny Recogne", "Catchment": "Yes"},
      {"Code": "6810", "Name": "Chiny Izel", "Catchment": "Yes"},
      {"Code": "6811", "Name": "Chiny Les Bulles", "Catchment": "Yes"},
      {"Code": "6812", "Name": "Chiny Suxy", "Catchment": "Yes"},
      {"Code": "6813", "Name": "Chiny Termes", "Catchment": "Yes"},
      {"Code": "6820", "Name": "Florenville", "Catchment": "Yes"},
      {"Code": "6821", "Name": "Florenville", "Catchment": "Yes"},
      {"Code": "6823", "Name": "Florenville", "Catchment": "Yes"},
      {"Code": "6824", "Name": "Florenville Chassepierre", "Catchment": "Yes"},
      {"Code": "6830", "Name": "Bouillon Les Hayons", "Catchment": "Yes"},
      {"Code": "6831", "Name": "Bouillon", "Catchment": "Yes"},
      {"Code": "6832", "Name": "Bouillon", "Catchment": "Yes"},
      {"Code": "6833", "Name": "Bouillon Vivy", "Catchment": "Yes"},
      {"Code": "6834", "Name": "Bouillon", "Catchment": "Yes"},
      {"Code": "6836", "Name": "Bouillon", "Catchment": "Yes"},
      {"Code": "6838", "Name": "Bouillon Corbion", "Catchment": "Yes"},
      {"Code": "6840", "Name": "Neufchâteau Hamipré", "Catchment": "Yes"},
      {"Code": "6850", "Name": "Paliseul", "Catchment": "Yes"},
      {"Code": "6851", "Name": "Paliseul Nollevaux", "Catchment": "Yes"},
      {"Code": "6852", "Name": "Paliseul Opont", "Catchment": "Yes"},
      {"Code": "6853", "Name": "Paliseul", "Catchment": "Yes"},
      {"Code": "6856", "Name": "Paliseul Faysles-Veneurs", "Catchment": "Yes"},
      {"Code": "6860", "Name": "Léglise", "Catchment": "Yes"},
      {"Code": "6870", "Name": "Saint-Hubert Hatrival", "Catchment": "Yes"},
      {"Code": "6880", "Name": "Bertrix Jehonville", "Catchment": "Yes"},
      {"Code": "6887", "Name": "Herbeumont Saint-Médard", "Catchment": "Yes"},
      {"Code": "6890", "Name": "Libin Transinne", "Catchment": "Yes"},
      {"Code": "6900", "Name": "Marche-en-Famenne Humain", "Catchment": "Yes"},
      {"Code": "6920", "Name": "Wellin", "Catchment": "Yes"},
      {"Code": "6921", "Name": "Wellin", "Catchment": "Yes"},
      {"Code": "6922", "Name": "Wellin Halma", "Catchment": "Yes"},
      {"Code": "6924", "Name": "Wellin", "Catchment": "Yes"},
      {"Code": "6927", "Name": "Tellin", "Catchment": "Yes"},
      {"Code": "6929", "Name": "Daverdisse Haut-Fays", "Catchment": "Yes"},
      {"Code": "6940", "Name": "Durbuy Wéris", "Catchment": "Yes"},
      {"Code": "6941", "Name": "Durbuy", "Catchment": "Yes"},
      {"Code": "6950", "Name": "Nassogne", "Catchment": "Yes"},
      {"Code": "6951", "Name": "Nassogne Bande", "Catchment": "Yes"},
      {"Code": "6952", "Name": "Nassogne Grune", "Catchment": "Yes"},
      {"Code": "6953", "Name": "Nassogne Lesterny", "Catchment": "Yes"},
      {"Code": "6960", "Name": "Manhay Harre", "Catchment": "Yes"},
      {"Code": "6970", "Name": "Tenneville", "Catchment": "Yes"},
      {"Code": "6971", "Name": "Tenneville", "Catchment": "Yes"},
      {"Code": "6972", "Name": "Tenneville", "Catchment": "Yes"},
      {"Code": "6980", "Name": "La Rocheen-Ardenne Beausaint", "Catchment": "Yes"},
      {"Code": "6982", "Name": "La Rocheen-Ardenne Samrée", "Catchment": "Yes"},
      {"Code": "6983", "Name": "La Rocheen-Ardenne", "Catchment": "Yes"},
      {"Code": "6984", "Name": "La Rocheen-Ardenne Hives", "Catchment": "Yes"},
      {"Code": "6986", "Name": "La Rocheen-Ardenne Halleux", "Catchment": "Yes"},
      {"Code": "6987", "Name": "Rendeux", "Catchment": "Yes"},
      {"Code": "6990", "Name": "Hotton Fronville", "Catchment": "Yes"},
      {"Code": "6997", "Name": "Erezée Mormont", "Catchment": "Yes"},
      {"Code": "7000", "Name": "Mons", "Catchment": "Yes"},
      {"Code": "7010", "Name": "S.H.A.P.E. Belgique", "Catchment": "Yes"},
      {"Code": "7011", "Name": "Mons", "Catchment": "Yes"},
      {"Code": "7012", "Name": "Mons Flénu", "Catchment": "Yes"},
      {"Code": "7020", "Name": "Mons Casteau,Maisières,Masnuy-Saint-Jean", "Catchment": "Yes"},
      {"Code": "7021", "Name": "Mons", "Catchment": "Yes"},
      {"Code": "7022", "Name": "Mons Mesvin", "Catchment": "Yes"},
      {"Code": "7024", "Name": "Mons", "Catchment": "Yes"},
      {"Code": "7030", "Name": "Mons", "Catchment": "Yes"},
      {"Code": "7031", "Name": "Mons", "Catchment": "Yes"},
      {"Code": "7032", "Name": "Mons Spiennes", "Catchment": "Yes"},
      {"Code": "7033", "Name": "Mons Cuesmes", "Catchment": "Yes"},
      {"Code": "7034", "Name": "Mons", "Catchment": "Yes"},
      {"Code": "7040", "Name": "Quévy Quévyle-Grand", "Catchment": "Yes"},
      {"Code": "7041", "Name": "Quévy Givry", "Catchment": "Yes"},
      {"Code": "7050", "Name": "Jurbise Erbaut", "Catchment": "Yes"},
      {"Code": "7060", "Name": "Soignies Horrues", "Catchment": "Yes"},
      {"Code": "7061", "Name": "Soignies Casteau", "Catchment": "Yes"},
      {"Code": "7062", "Name": "Soignies Naast", "Catchment": "Yes"},
      {"Code": "7063", "Name": "Soignies", "Catchment": "Yes"},
      {"Code": "7070", "Name": "Le Roeulx Thieu", "Catchment": "Yes"},
      {"Code": "7080", "Name": "Frameries Sarsla-Bruyère", "Catchment": "Yes"},
      {"Code": "7090", "Name": "Brainele-Comte Ronquières", "Catchment": "Yes"},
      {"Code": "7100", "Name": "La Louvière Saint-Vaast", "Catchment": "Yes"},
      {"Code": "7110", "Name": "La Louvière Houdeng-Goegnies", "Catchment": "Yes"},
      {"Code": "7120", "Name": "Estinnes Estinnesau-Val", "Catchment": "Yes"},
      {"Code": "7130", "Name": "Binche", "Catchment": "Yes"},
      {"Code": "7131", "Name": "Binche", "Catchment": "Yes"},
      {"Code": "7133", "Name": "Binche", "Catchment": "Yes"},
      {"Code": "7134", "Name": "Binche Leval-Trahegnies", "Catchment": "Yes"},
      {"Code": "7140", "Name": "Morlanwelz", "Catchment": "Yes"},
      {"Code": "7141", "Name": "Morlanwelz Mont-Sainte-Aldegonde", "Catchment": "Yes"},
      {"Code": "7160", "Name": "Chapellelez-Herlaimont Godarville", "Catchment": "Yes"},
      {"Code": "7170", "Name": "Manage Boisd'Haine", "Catchment": "Yes"},
      {"Code": "7180", "Name": "Seneffe", "Catchment": "Yes"},
      {"Code": "7181", "Name": "Seneffe Familleureux", "Catchment": "Yes"},
      {"Code": "7190", "Name": "Ecaussinnes", "Catchment": "Yes"},
      {"Code": "7191", "Name": "Ecaussinnes Ecaussinnes-Lalaing", "Catchment": "Yes"},
      {"Code": "7300", "Name": "Boussu", "Catchment": "Yes"},
      {"Code": "7301", "Name": "Boussu Hornu", "Catchment": "Yes"},
      {"Code": "7320", "Name": "Bernissart", "Catchment": "Yes"},
      {"Code": "7321", "Name": "Bernissart", "Catchment": "Yes"},
      {"Code": "7322", "Name": "Bernissart Pommeroeul", "Catchment": "Yes"},
      {"Code": "7330", "Name": "Saint-Ghislain", "Catchment": "Yes"},
      {"Code": "7331", "Name": "Saint-Ghislain Baudour", "Catchment": "Yes"},
      {"Code": "7332", "Name": "Saint-Ghislain", "Catchment": "Yes"},
      {"Code": "7333", "Name": "Saint-Ghislain Tertre", "Catchment": "Yes"},
      {"Code": "7334", "Name": "Saint-Ghislain Villerot", "Catchment": "Yes"},
      {"Code": "7340", "Name": "Colfontaine Pâturages", "Catchment": "Yes"},
      {"Code": "7350", "Name": "Hensies Montroeulsur-Haine", "Catchment": "Yes"},
      {"Code": "7370", "Name": "Dour Elouges", "Catchment": "Yes"},
      {"Code": "7380", "Name": "Quiévrain Baisieux", "Catchment": "Yes"},
      {"Code": "7382", "Name": "Quiévrain", "Catchment": "Yes"},
      {"Code": "7387", "Name": "Honnelles Angreau", "Catchment": "Yes"},
      {"Code": "7390", "Name": "Quaregnon", "Catchment": "Yes"},
      {"Code": "7500", "Name": "Tournai Ere", "Catchment": "Yes"},
      {"Code": "7501", "Name": "Tournai", "Catchment": "Yes"},
      {"Code": "7502", "Name": "Tournai", "Catchment": "Yes"},
      {"Code": "7503", "Name": "Tournai", "Catchment": "Yes"},
      {"Code": "7504", "Name": "Tournai", "Catchment": "Yes"},
      {"Code": "7506", "Name": "Tournai Willemeau", "Catchment": "Yes"},
      {"Code": "7520", "Name": "Tournai Ramegnies-Chin", "Catchment": "Yes"},
      {"Code": "7521", "Name": "Tournai Chercq", "Catchment": "Yes"},
      {"Code": "7522", "Name": "Tournai Marquain", "Catchment": "Yes"},
      {"Code": "7530", "Name": "Tournai", "Catchment": "Yes"},
      {"Code": "7531", "Name": "Tournai Havinnes", "Catchment": "Yes"},
      {"Code": "7532", "Name": "Tournai Beclers", "Catchment": "Yes"},
      {"Code": "7533", "Name": "Tournai Thimougies", "Catchment": "Yes"},
      {"Code": "7534", "Name": "Tournai", "Catchment": "Yes"},
      {"Code": "7536", "Name": "Tournai", "Catchment": "Yes"},
      {"Code": "7538", "Name": "Tournai Vezon", "Catchment": "Yes"},
      {"Code": "7540", "Name": "Tournai", "Catchment": "Yes"},
      {"Code": "7542", "Name": "Tournai Mont-Saint-Aubert", "Catchment": "Yes"},
      {"Code": "7543", "Name": "Tournai", "Catchment": "Yes"},
      {"Code": "7548", "Name": "Tournai", "Catchment": "Yes"},
      {"Code": "7600", "Name": "Péruwelz", "Catchment": "Yes"},
      {"Code": "7601", "Name": "Péruwelz Roucourt", "Catchment": "Yes"},
      {"Code": "7602", "Name": "Péruwelz", "Catchment": "Yes"},
      {"Code": "7603", "Name": "Péruwelz", "Catchment": "Yes"},
      {"Code": "7604", "Name": "Péruwelz", "Catchment": "Yes"},
      {"Code": "7608", "Name": "Péruwelz", "Catchment": "Yes"},
      {"Code": "7610", "Name": "Rumes", "Catchment": "Yes"},
      {"Code": "7611", "Name": "Rumes", "Catchment": "Yes"},
      {"Code": "7618", "Name": "Rumes Taintignies", "Catchment": "Yes"},
      {"Code": "7620", "Name": "Brunehaut", "Catchment": "Yes"},
      {"Code": "7621", "Name": "Brunehaut Lesdain", "Catchment": "Yes"},
      {"Code": "7622", "Name": "Brunehaut Laplaigne", "Catchment": "Yes"},
      {"Code": "7623", "Name": "Brunehaut Rongy", "Catchment": "Yes"},
      {"Code": "7624", "Name": "Brunehaut", "Catchment": "Yes"},
      {"Code": "7640", "Name": "Antoing Péronneslez-Antoing", "Catchment": "Yes"},
      {"Code": "7641", "Name": "Antoing", "Catchment": "Yes"},
      {"Code": "7642", "Name": "Antoing", "Catchment": "Yes"},
      {"Code": "7643", "Name": "Antoing", "Catchment": "Yes"},
      {"Code": "7700", "Name": "Mouscron", "Catchment": "Yes"},
      {"Code": "7711", "Name": "Mouscron Dottignies", "Catchment": "Yes"},
      {"Code": "7712", "Name": "Mouscron Herseaux", "Catchment": "Yes"},
      {"Code": "7730", "Name": "Estaimpuis Evregnies", "Catchment": "Yes"},
      {"Code": "7740", "Name": "Pecq Warcoing", "Catchment": "Yes"},
      {"Code": "7742", "Name": "Pecq Hérinneslez-Pecq", "Catchment": "Yes"},
      {"Code": "7743", "Name": "Pecq Esquelmes", "Catchment": "Yes"},
      {"Code": "7750", "Name": "Montdel'Enclus Russeignies", "Catchment": "Yes"},
      {"Code": "7760", "Name": "Celles Escanaffles", "Catchment": "Yes"},
      {"Code": "7780", "Name": "Comines-Warneton", "Catchment": "Yes"},
      {"Code": "7781", "Name": "Comines-Warneton", "Catchment": "Yes"},
      {"Code": "7782", "Name": "Comines-Warneton", "Catchment": "Yes"},
      {"Code": "7783", "Name": "Comines-Warneton", "Catchment": "Yes"},
      {"Code": "7784", "Name": "Comines-Warneton Warneton", "Catchment": "Yes"},
      {"Code": "7800", "Name": "Ath Lanquesaint", "Catchment": "Yes"},
      {"Code": "7801", "Name": "Ath Irchonwelz", "Catchment": "Yes"},
      {"Code": "7802", "Name": "Ath", "Catchment": "Yes"},
      {"Code": "7803", "Name": "Ath", "Catchment": "Yes"},
      {"Code": "7804", "Name": "Ath Ostiches", "Catchment": "Yes"},
      {"Code": "7810", "Name": "Ath", "Catchment": "Yes"},
      {"Code": "7811", "Name": "Ath", "Catchment": "Yes"},
      {"Code": "7812", "Name": "Ath Villers-Saint-Amand", "Catchment": "Yes"},
      {"Code": "7822", "Name": "Ath", "Catchment": "Yes"},
      {"Code": "7823", "Name": "Ath Gibecq", "Catchment": "Yes"},
      {"Code": "7830", "Name": "Silly Gondregnies", "Catchment": "Yes"},
      {"Code": "7850", "Name": "Enghien", "Catchment": "Yes"},
      {"Code": "7860", "Name": "Lessines", "Catchment": "Yes"},
      {"Code": "7861", "Name": "Lessines Papignies", "Catchment": "Yes"},
      {"Code": "7862", "Name": "Lessines", "Catchment": "Yes"},
      {"Code": "7863", "Name": "Lessines Ghoy", "Catchment": "Yes"},
      {"Code": "7864", "Name": "Lessines", "Catchment": "Yes"},
      {"Code": "7866", "Name": "Lessines Boisde-Lessines", "Catchment": "Yes"},
      {"Code": "7870", "Name": "Lens Cambron-Saint-Vincent", "Catchment": "Yes"},
      {"Code": "7880", "Name": "Flobecq", "Catchment": "Yes"},
      {"Code": "7890", "Name": "Ellezelles", "Catchment": "Yes"},
      {"Code": "7900", "Name": "Leuzeen-Hainaut", "Catchment": "Yes"},
      {"Code": "7901", "Name": "Leuzeen-Hainaut Thieulain", "Catchment": "Yes"},
      {"Code": "7903", "Name": "Leuzeen-Hainaut Chapelleà-Oie", "Catchment": "Yes"},
      {"Code": "7904", "Name": "Leuzeen-Hainaut Willaupuis", "Catchment": "Yes"},
      {"Code": "7906", "Name": "Leuzeen-Hainaut", "Catchment": "Yes"},
      {"Code": "7910", "Name": "Frasneslez-Anvaing Anvaing", "Catchment": "Yes"},
      {"Code": "7911", "Name": "Frasneslez-Anvaing Oeudeghien", "Catchment": "Yes"},
      {"Code": "7912", "Name": "Frasneslez-Anvaing Dergneau", "Catchment": "Yes"},
      {"Code": "7940", "Name": "Brugelette Cambron-Casteau", "Catchment": "Yes"},
      {"Code": "7941", "Name": "Brugelette Attre", "Catchment": "Yes"},
      {"Code": "7942", "Name": "Brugelette Mévergnieslez-Lens", "Catchment": "Yes"},
      {"Code": "7943", "Name": "Brugelette Gages", "Catchment": "Yes"},
      {"Code": "7950", "Name": "Chièvres", "Catchment": "Yes"},
      {"Code": "7951", "Name": "Chièvres", "Catchment": "Yes"},
      {"Code": "7970", "Name": "Beloeil", "Catchment": "Yes"},
      {"Code": "7971", "Name": "Beloeil Ramegnies", "Catchment": "Yes"},
      {"Code": "7972", "Name": "Beloeil Ellignies-Sainte-Anne", "Catchment": "Yes"},
      {"Code": "7973", "Name": "Beloeil Grandglise", "Catchment": "Yes"},
      {"Code": "1100", "Name": "Postcheque", "Catchment": "Yes"},
      {"Code": "1105", "Name": "SOC", "Catchment": "Yes"},
      {"Code": "4090", "Name": "F.B.A. (Forces Belges en Allemagne)", "Catchment": "Yes"}      
]
    `;
